import re

# ── As mesmas 4 categorias de fabricação que auditamos manualmente ──────────

def find_fabricated_cdna(text):
    """cDNA notation (c.NNNN[base]>[base]) -- nenhuma coluna do pipeline
    carrega HGVS-c, então qualquer ocorrência é não-sourced."""
    return re.findall(r"c\.\d+[ACGT]>[ACGT]", text)

def find_unfilled_placeholder(text):
    """Placeholder de template vazando ('c.[Variant]', 'c.[nucleotide
    change not provided]')."""
    return re.findall(r"c\.\[[^\]]{0,60}\]", text)

def find_mondo_ids(text):
    """MONDO IDs -- não existe coluna 'mondo_id' no pipeline; só omim_primary."""
    return re.findall(r"MONDO:\d+", text)

UNSUPPORTED_EVIDENCE_PHRASES = [
    "de novo", "segregat", "robust evidence", "strong genetic evidence",
    "functional studies demonstrating", "clinical phenotypes typically",
    "particularly high risk", "well-established in vitro",
    "established literature indicates", "literature indicates that",
]

def find_unsupported_evidence(text):
    lower = text.lower()
    return [p for p in UNSUPPORTED_EVIDENCE_PHRASES if p in lower]


def flag_completion(text):
    flags = {
        "cdna_fabricado": find_fabricated_cdna(text),
        "placeholder_vazando": find_unfilled_placeholder(text),
        "mondo_id": find_mondo_ids(text),
        "evidencia_nao_sustentada": find_unsupported_evidence(text),
    }
    total = sum(len(v) for v in flags.values())
    return flags, total


# ── Testes contra texto REAL já confirmado nesta conversa ───────────────────

REAL_CASES = {
    "RIT1 p.Phe82Val -- ON (deve pegar cDNA)": (
        "Variant Prioritization Assessment: RIT1 c.244T>G (p.Phe82Val)... "
        "The concordance across five distinct predictive algorithms...",
        True,  # esperado: flagged
    ),
    "RIT1 p.Phe82Val -- OFF (deve ficar limpo)": (
        "Variant Prioritization Assessment Variant Identification Gene: RIT1 "
        "Protein Variant: ENSP00000357306.3:p.Phe82Val ClinVar Variation ID: 183408 "
        "Computational Evidence Investigation Score: 11 CADD PHRED: 31.0",
        False,
    ),
    "BRAF p.Gly464Val -- ON (evidência fabricada)": (
        "This classification reflects strong published genetic evidence "
        "(including multiple de novo and inherited cases) and consistent "
        "mechanistic data.",
        True,
    ),
    "BRAF p.Gly464Val -- OFF (limpo)": (
        "Computational Evidence The following metrics were generated by the "
        "unified RASopathy VUS Series pipeline...",
        False,
    ),
    "MAP2K2 p.Ser248Trp -- ON (placeholder vazando)": (
        "Variant Prioritization Report: MAP2K2 c.[nucleotide change not provided] "
        "p.Ser248Trp",
        True,
    ),
    "SOS2 p.Arg645Trp -- OFF (evidência clínica fabricada mesmo sem Rephrase)": (
        "Literature indicates that pathogenic SOS2 variants are a rare cause of "
        "Noonan syndrome... clinical phenotypes typically include short stature, "
        "characteristic facial features, and congenital heart defects... "
        "particularly high risk for lymphatic complications.",
        True,
    ),
    "RAF1 p.Thr452Lys -- OFF (MONDO inserido)": (
        "MONDO:0018997: Noonan syndrome (broader entity) MONDO:0012690: "
        "Noonan syndrome 5 (RAF1-related Noonan syndrome)",
        True,
    ),
}

print(f"{'Caso':<55} {'Esperado':<10} {'Obtido':<10} {'Flags'}")
print("-" * 100)
all_ok = True
for label, (text, expected_flagged) in REAL_CASES.items():
    flags, total = flag_completion(text)
    got_flagged = total > 0
    ok = got_flagged == expected_flagged
    all_ok &= ok
    mark = "✓" if ok else "✗ ERRO"
    detail = ", ".join(f"{k}={v}" for k, v in flags.items() if v)
    print(f"{label:<55} {str(expected_flagged):<10} {str(got_flagged):<10} {mark} {detail}")

print()
print("TODOS OS CASOS PASSARAM" if all_ok else "⚠ ALGUM CASO FALHOU -- revisar regex")
