# -*- coding: utf-8 -*-
"""improved

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-kXG89PwMmnjTgERMXy0lvMmUGIMEEK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gradio as gr
import joblib

from tensorflow.keras.models import load_model

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

model = load_model(
    "0.74.HANNDA_FINAL_5FEATURE_MODEL.h5"
)

x_scaler = joblib.load(
    "0.74x_scaler_5feature.pkl"
)

y_scaler = joblib.load(
    "0.74y_scaler_5feature.pkl"
)

test_df_raw = pd.read_excel(
    "TESTING.xlsx"
)

test_df = (
    test_df_raw
    .iloc[1:]
    .reset_index(drop=True)
)

test_df = test_df.apply(
    pd.to_numeric,
    errors="coerce"
)

test_df = test_df.fillna(0.0)

print(test_df.shape)

test_rain = test_df.iloc[:,1:25].values

test_up_depth = test_df.iloc[:,26:50].values

test_up_velocity = test_df.iloc[:,51:75].values

test_bridge_depth = test_df.iloc[:,76:100].values

test_bridge_velocity = test_df.iloc[:,101:125].values

test_rain_series = test_rain.flatten()

test_up_depth_series = test_up_depth.flatten()

test_up_velocity_series = test_up_velocity.flatten()

test_bridge_velocity_series = test_bridge_velocity.flatten()

test_bridge_depth_series = test_bridge_depth.flatten()

window = 24

X_test = []
y_test = []

for i in range(
    len(test_rain_series) - window
):

    X_test.append(
        np.stack([
            test_rain_series[i:i+window],
            test_up_depth_series[i:i+window],
            test_up_velocity_series[i:i+window],
            test_bridge_velocity_series[i:i+window],
            test_bridge_depth_series[i:i+window]
        ], axis=1)
    )

    y_test.append(
        test_bridge_depth_series[i+window]
    )

X_test = np.array(X_test)

y_test = np.array(y_test)

n_samples, n_timesteps, n_features = X_test.shape

X_test_scaled = x_scaler.transform(
    X_test.reshape(-1, n_features)
).reshape(
    n_samples,
    n_timesteps,
    n_features
)

y_pred_scaled = model.predict(
    X_test_scaled
)

y_pred = y_scaler.inverse_transform(
    y_pred_scaled
)

y_pred = np.clip(
    y_pred,
    0,
    None
)

y_pred = y_pred.flatten()

y_test = y_test.flatten()

overall_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

overall_mae = mean_absolute_error(
    y_test,
    y_pred
)

overall_r2 = r2_score(
    y_test,
    y_pred
)

overall_nse = 1 - np.sum(
    (y_test - y_pred)**2
) / np.sum(
    (y_test - np.mean(y_test))**2
)

print("RMSE:", overall_rmse)
print("MAE :", overall_mae)
print("R²  :", overall_r2)
print("NSE :", overall_nse)

def validation_segment(
    start_idx,
    length
):

    start_idx = int(start_idx)

    length = int(length)

    end_idx = min(
        start_idx + length,
        len(y_test)
    )

    actual = y_test[
        start_idx:end_idx
    ]

    predicted = y_pred[
        start_idx:end_idx
    ]
    rainfall = test_rain_series[
        start_idx:end_idx
    ]
    rmse = np.sqrt(
        mean_squared_error(
            actual,
            predicted
        )
    )

    mae = mean_absolute_error(
        actual,
        predicted
    )

    r2 = r2_score(
        actual,
        predicted
    )

    nse = 1 - np.sum(
        (actual - predicted)**2
    ) / np.sum(
        (actual - np.mean(actual))**2
    )
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(10,7)
    )

    ax_rain = axes[0]

    ax_rain.bar(
        range(len(rainfall)),
        rainfall
    )

    ax_rain.set_title(
        "Validation Rainfall"
    )

    ax_rain.set_ylabel(
        "Rainfall (mm)"
    )

    ax_rain.grid(True)

    ax_flood = axes[1]

    ax_flood.plot(
        actual,
        label="Actual"
    )

    ax_flood.plot(
        predicted,
        label="Predicted"
    )

    ax_flood.set_title(
        "Actual vs Predicted Flood Depth"
    )

    ax_flood.set_ylabel(
        "Depth (m)"
    )

    ax_flood.grid(True)

    ax_flood.legend()
    plt.tight_layout()
    return (
        fig,
        f"{rmse:.4f}",
        f"{mae:.4f}",
        f"{r2:.4f}",
        f"{nse:.4f}"
    )

VALIDATION_CASES = {

    "Case A (0-99)": 0,

    "Case B (300-399)": 300,

    "Case C (600-699)": 600,

    "Case D (900-999)": 900,

    "Case E (1200-1299)": 1200

}

def validation_dashboard(
    selected_case
):

    start_idx = VALIDATION_CASES[
        selected_case
    ]

    fig, rmse, mae, r2, nse = validation_segment(
        start_idx,
        100
    )

    interpretation = interpret_case_metrics(
        float(rmse),
        float(mae),
        float(r2),
        float(nse)
    )

    return (
        fig,
        rmse,
        mae,
        r2,
        nse,
        interpretation
    )

HYDRAULIC_STATES = {

    "Dry": {
        "up_depth": 0.0000,
        "up_vel": 0.0000,
        "bridge_vel": 0.0678,
        "bridge_depth": 0.1093
    },

    "Normal": {
        "up_depth": 0.1765,
        "up_vel": 0.0148,
        "bridge_vel": 0.0931,
        "bridge_depth": 0.2824
    },

    "Wet": {
        "up_depth": 0.4117,
        "up_vel": 0.0327,
        "bridge_vel": 0.1182,
        "bridge_depth": 0.6218
    },

    "Flooded": {
        "up_depth": 0.8106,
        "up_vel": 0.0633,
        "bridge_vel": 0.2021,
        "bridge_depth": 0.8293
    }

}

def classify_risk(depth):

    if depth < 0.30:
        return "LOW"

    elif depth < 0.75:
        return "MODERATE"

    elif depth < 1.50:
        return "HIGH"

    return "SEVERE"


def warning_message(depth):

    if depth < 0.30:
        return "No significant flooding expected."

    elif depth < 0.75:
        return "Localized shallow flooding may occur."

    elif depth < 1.50:
        return "Flooding may affect roads and low-lying areas."

    return "Significant flooding likely. Immediate monitoring advised."

def predict_flood_depth(
    rainfall_24h,
    state
):

    rainfall_24h = np.array(
        rainfall_24h,
        dtype=float
    )

    if len(rainfall_24h) != 24:
        raise ValueError(
            "Exactly 24 rainfall values required."
        )

    window = np.column_stack([

        rainfall_24h,

        np.full(
            24,
            state["up_depth"]
        ),

        np.full(
            24,
            state["up_vel"]
        ),

        np.full(
            24,
            state["bridge_vel"]
        ),

        np.full(
            24,
            state["bridge_depth"]
        )

    ])

    window_scaled = x_scaler.transform(
        window.reshape(-1,5)
    ).reshape(1,24,5)

    pred_scaled = model.predict(
        window_scaled,
        verbose=0
    )

    pred_depth = y_scaler.inverse_transform(
        pred_scaled
    )[0,0]

    risk = classify_risk(
        pred_depth
    )

    return pred_depth, risk

from datetime import timedelta

def predict_flood_series(
    rainfall_values,
    start_datetime,
    state
):

    rainfall_values = np.array(
        rainfall_values,
        dtype=float
    )

    predictions = []

    forecast_times = []

    for i in range(
        len(rainfall_values) - 24 + 1
    ):

        rain_window = rainfall_values[
            i:i+24
        ]

        pred_depth, _ = predict_flood_depth(
            rain_window,
            state
        )

        predictions.append(
            pred_depth
        )

        forecast_times.append(
            start_datetime
            + timedelta(hours=i+24)
        )

    return (
        forecast_times,
        np.array(predictions)
    )

def forecast_from_text(
    rainfall_text,
    start_datetime,
    river_condition
):

    rainfall_values = [

        float(x.strip())

        for x in rainfall_text.replace(
            "\n",
            ","
        ).split(",")

        if x.strip()
    ]

    if len(rainfall_values) < 24:

        raise ValueError(
            "Please enter at least 24 hourly rainfall values."
        )

    start_datetime = pd.to_datetime(
        start_datetime
    )

    from datetime import timedelta


    state = HYDRAULIC_STATES[
        river_condition
    ]

    times, predictions = predict_flood_series(
        rainfall_values,
        start_datetime,
        state
    )
    forecast_table = pd.DataFrame({

        "Forecast Time": times,

        "Predicted Depth (MSL,m)": [
            round(float(x), 3)
            for x in predictions
        ]

    })

    peak_depth = float(
        np.max(predictions)
    )

    peak_index = int(
        np.argmax(predictions)
    )

    peak_time = str(
        times[peak_index]
    )

    risk = classify_risk(
        peak_depth
    )

    advisory = warning_message(
        peak_depth
    )

        # ==========================================================
    # Combined Rainfall–Flood Hydrograph
    # ==========================================================

    # ==========================================================
# Combined Rainfall–Flood Hydrograph
# ==========================================================

    import matplotlib.dates as mdates
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D

    fig, ax_depth = plt.subplots(figsize=(12,5))

    # ---------------------------------------
    # Flood Hydrograph
    # ---------------------------------------
    ax_depth.plot(
        times,
        predictions,
        color="crimson",
        linewidth=3,
        marker="o",
        markersize=4,
        zorder=5
    )

    ax_depth.set_ylabel(
        "Flood Depth (m)",
        fontsize=11,
        color="crimson"
    )

    ax_depth.tick_params(
        axis="y",
        labelcolor="crimson"
    )

    ax_depth.grid(
        linestyle="--",
        alpha=0.35
    )
    ax_depth.set_ylim(
        min(predictions)-0.001,
        max(predictions)+0.002
    )

    # ---------------------------------------
    # Rainfall Hyetograph
    # ---------------------------------------

    ax_rain = ax_depth.twinx()

    # rainfall that corresponds to each prediction
    rain_forecast = rainfall_values[23:]

    assert len(rain_forecast) == len(times), \
        "Rainfall and prediction lengths do not match."

    ax_rain.bar(
        times,
        rain_forecast,
        width=0.009,
        color="royalblue",
        edgecolor="none",
        alpha=0.45,
        zorder=1
    )

    # Inverted rainfall axis
    ax_rain.set_ylim(max(rain_forecast)*1.2, 0)

    ax_rain.set_ylabel(
        "Rainfall (mm)",
        fontsize=11,
        color="royalblue"
    )

    ax_rain.tick_params(
        axis="y",
        labelcolor="royalblue"
    )

    # ---------------------------------------
    # Formatting
    # ---------------------------------------

    ax_depth.set_title(
        "Rainfall Hyetograph and Flood Forecast",
        fontsize=15,
        weight="bold"
    )

    ax_depth.xaxis.set_major_formatter(
        mdates.DateFormatter("%m-%d %H")
    )

    plt.setp(
        ax_depth.get_xticklabels(),
        rotation=45,
        ha="right"
    )

    legend_handles = [

        Patch(
            facecolor="royalblue",
            edgecolor="navy",
            label="Rainfall"
        ),

        Line2D(
            [0],
            [0],
            color="crimson",
            lw=3,
            marker="o",
            markersize=4,
            label="Flood Depth"
        )

    ]

    ax_depth.legend(
        handles=legend_handles,
        loc="upper left",
        bbox_to_anchor=(0.009,0.99)
    )

    plt.tight_layout()


    return (

        fig,

        forecast_table,

        f"{peak_depth:.3f} m",

        peak_time,

        risk,

        advisory

    )

sample_rainfall = "\n".join(
    map(
        str,
        test_rain.flatten()[:48]
    )
)

OVERALL_RESULTS = f"""
Overall Testing Performance

RMSE : {overall_rmse:.4f}
MAE  : {overall_mae:.4f}
R²   : {overall_r2:.4f}
NSE  : {overall_nse:.4f}
"""

MODEL_INTERPRETATION = f"""
Interpretation

• RMSE = {overall_rmse:.4f} m indicates very low prediction error.

• MAE = {overall_mae:.4f} m indicates an average prediction error of approximately {overall_mae*100:.2f} cm.

• R² = {overall_r2:.4f} indicates that {overall_r2*100:.2f}% of the variance in observed flood depths is explained by the model.

• NSE = {overall_nse:.4f} indicates excellent predictive performance and strong agreement between observed and predicted flood depths.

Overall, the developed ANN model demonstrates high accuracy and reliability for flood depth forecasting within the testing dataset.
"""

forecast_from_text(
    sample_rainfall,
    "2025-07-15 00:00",
    "Normal"
)


# 1. Define the Beautiful CSS Theme first
custom_css = """
.gradio-container {background-color: #f0f4f8;}
.result-card {
    border-radius: 20px !important;
    padding: 20px !important;
    background: white !important;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1) !important;
    margin-bottom: 10px;
}
.header-text {text-align: center; color: #1a365d;}
.sub-header {color: #2c5282; font-weight: bold;}
"""

# 2. Start the App with the Theme and CSS
with gr.Blocks(title="HANNDA Flood Forecasting System", css=custom_css, theme=gr.themes.Soft()) as demo:

    gr.Markdown("#HANNDA Flood Forecasting System", elem_classes="header-text")
    gr.Markdown("<p style='text-align: center;'><b>Forecast Method:</b> The model uses a 24-hour rolling rainfall window and hydraulic state conditions to predict bridge flood depth.</p>")

    # --- TAB 1: FLOOD FORECASTING ---
    with gr.Tab("Flood Forecasting"):
        with gr.Row():

            # LEFT COLUMN: Inputs & Instructions
            with gr.Column(scale=1, elem_classes="result-card"):
                gr.Markdown("### ⚙️ System Inputs", elem_classes="sub-header")
                gr.Markdown("Enter 24+ hourly rainfall values (comma-separated or line breaks). Select the initial river condition.")

                rainfall_input = gr.Textbox(label="Rainfall Values (mm)", lines=5, value=sample_rainfall)
                start_datetime = gr.Textbox(label="Forecast Start Date & Time", value="2025-07-15 00:00")
                river_condition = gr.Dropdown(
                    choices=["Dry", "Normal", "Wet", "Flooded"],
                    value="Normal",
                    label="River Condition"
                )
                submit_btn = gr.Button("Generate Forecast", variant="primary")

                with gr.Accordion("Model Information", open=False):
                    gr.Markdown("""**Architecture:** ANN<br>**Features:** Rainfall, Upstream Depth/Velocity, Bridge Depth/Velocity<br>**Input Window:** 24 Hours""")

            # CENTER COLUMN: Visuals & Maps
            with gr.Column(scale=1, elem_classes="result-card"):
                gr.Markdown("### 📍 Location & Forecast Visuals", elem_classes="sub-header")
                # ADDED: The map/bridge image you wanted! Make sure you have this image in your folder.
                gr.Image("mandulog_bridge_1.png", label="Mandulog Bridge 1 / River Basin Context")
                combined_plot = gr.Plot(
                )

            # RIGHT COLUMN: Results & Warnings
            with gr.Column(scale=1, elem_classes="result-card"):
                gr.Markdown("### 🚨 Forecast Results", elem_classes="sub-header")
                risk = gr.Textbox(label="Risk Level")
                advisory = gr.Textbox(label="Flood Advisory")
                peak_depth = gr.Textbox(label="Peak Flood Depth")
                peak_time = gr.Textbox(label="Time of Peak")
                forecast_table = gr.Dataframe(label="Detailed Forecast Table", max_height=300)

                gr.Markdown("**Disclaimer:** This system is for research and decision-support purposes and should not replace official flood warning systems.")

        # Bind the click function for Tab 1
        submit_btn.click(
            fn=forecast_from_text,
            inputs=[rainfall_input, start_datetime, river_condition],
            outputs=[
                combined_plot,
                forecast_table,
                peak_depth,
                peak_time,
                risk,
                advisory
            ]
        )

    # --- TAB 2: MODEL VALIDATION ---
    with gr.Tab("Model Validation"):
        with gr.Row():

            # LEFT COLUMN: Overall Testing Metrics
            with gr.Column(scale=1, elem_classes="result-card"):
                gr.Markdown("### 📊 Overall Testing Performance", elem_classes="sub-header")
                gr.Markdown(f"""
                | Metric | Value |
                |---------|---------|
                | **RMSE** | {overall_rmse:.4f} m |
                | **MAE** | {overall_mae:.4f} m |
                | **R²** | {overall_r2:.4f} |
                | **NSE** | {overall_nse:.4f} |
                """)

                gr.Markdown(f"""
                **Interpretation:**
                • **RMSE:** Errors are generally < 3 cm.
                • **MAE:** Average error is **{overall_mae*100:.2f} cm**.
                • **R²:** **{overall_r2*100:.2f}%** of variability is explained.
                • **NSE:** Strong agreement between observed and predicted depths.

                *Overall, the developed ANN model demonstrates high accuracy and reliability.*
                """)

            # RIGHT COLUMN: Validation Cases
            with gr.Column(scale=2, elem_classes="result-card"):
                gr.Markdown("### 🔍 Validation Case Studies", elem_classes="sub-header")
                gr.Markdown("Validation cases represent different 100-sample segments to visualize performance across varying flood conditions.")

                validation_case = gr.Dropdown(
                    choices=list(VALIDATION_CASES.keys()),
                    value="Case A (0-99)",
                    label="Select Validation Case"
                )
                validation_plot = gr.Plot()

                with gr.Row():
                    rmse_box = gr.Textbox(label="RMSE", scale=1)
                    mae_box = gr.Textbox(label="MAE", scale=1)
                    r2_box = gr.Textbox(label="R²", scale=1)
                    nse_box = gr.Textbox(label="NSE", scale=1)

                case_interpretation = gr.Textbox(label="Case Interpretation", lines=4)

        # Bind the change function for Tab 2
        validation_case.change(
            fn=validation_dashboard,
            inputs=[validation_case],
            outputs=[validation_plot, rmse_box, mae_box, r2_box, nse_box, case_interpretation]
        )



import folium

def create_iligan_map():

    m = folium.Map(
        location=[8.23, 124.25],
        zoom_start=12,
        tiles="CartoDB Positron"
    )

    # Forecasting point
    folium.Marker(
        [8.1945, 124.2215],
        popup="Mandulog Bridge",
        tooltip="Forecasting Location",
        icon=folium.Icon(color="red")
    ).add_to(m)

    # Rainfall extraction point
    folium.Marker(
        [7.9, 124.6],
        popup="GSMaP Rainfall Point",
        tooltip="Rainfall Input Source",
        icon=folium.Icon(color="blue")
    ).add_to(m)

    return m._repr_html_()

import gradio as gr
from PIL import Image

# 1. Define the Beautiful CSS Theme
custom_css = """
.gradio-container {background-color: #f0f4f8;}
.result-card {
    border-radius: 20px !important;
    padding: 20px !important;
    background: white !important;
    box-shadow: 0 5px 15px rgba(0,0,0,0.1) !important;
    margin-bottom: 10px;
}
.header-text {text-align: center; color: #1a365d;}
.sub-header {color: #2c5282; font-weight: bold;}
"""

# 2. Launch the Application Block
with gr.Blocks(title="HANNDA Flood Forecasting System", css=custom_css, theme=gr.themes.Soft()) as demo:

    # --- HEADER ---
    gr.Markdown("#  HANNDA Flood Forecasting System", elem_classes="header-text")
    gr.Markdown("<p style='text-align: center;'><b>Forecast Method:</b> The model uses a 24-hour rolling rainfall window and hydraulic state conditions to predict bridge flood depth.</p>")

    # ==========================================
    # TAB 1: FLOOD FORECASTING
    # ==========================================
    with gr.Tab("Flood Forecasting"):
        with gr.Row():

            # ==========================================
            # LEFT COLUMN: MAP / IMAGE ONLY
            # ==========================================
            with gr.Column(scale=1, elem_classes="result-card"):

                gr.Markdown("### 📍 Watershed Location")

                try:
                    bridge_img = Image.open("mandulog_bridge_1.png")

                    gr.Image(
                        value=bridge_img,
                        interactive=False,
                        height=500,
                        label="Mandulog Watershed"
                    )

                except FileNotFoundError:
                    gr.Markdown("Image not found")

                gr.Markdown("### 🗺️ Iligan City Map")

                map_html = create_iligan_map()

                gr.HTML(
                    value=map_html,
                    min_height=450
                )
            # ==========================================
            # CENTER COLUMN: INPUTS + PLOTS
            # ==========================================
            with gr.Column(scale=3, elem_classes="result-card"):

                gr.Markdown("### ⚙️ System Inputs", elem_classes="sub-header")

                gr.Markdown("""
                **Instructions**
                • Enter hourly rainfall values separated by commas or line breaks.
                • Minimum required input: 24 hourly rainfall values.
                • River Condition represents predefined hydraulic states derived from HEC-RAS simulations and used to initialize ANN inputs.
                """)

                rainfall_input = gr.Textbox(
                    label="Rainfall Values (mm)",
                    lines=5,
                    value=sample_rainfall
                )

                start_datetime = gr.Textbox(
                    label="Forecast Start Date & Time",
                    value="2025-07-15 00:00"
                )

                river_condition = gr.Dropdown(
                    choices=["Dry", "Normal", "Wet", "Flooded"],
                    value="Normal",
                    label="River Condition"
                )

                submit_btn = gr.Button(
                    "Generate Forecast",
                    variant="primary"
                )

                with gr.Accordion("Model Information", open=False):
                    gr.Markdown("""
                    **Architecture:** Artificial Neural Network (ANN)

                    **Input Features**
                    - Rainfall
                    - Upstream Depth / Velocity
                    - Bridge Depth / Velocity

                    **Input Window:** 24 Hours

                    **Output:** Predicted Bridge Flood Depth
                    """)

                gr.Markdown("### 📈 Forecast Visuals", elem_classes="sub-header")
                combined_plot = gr.Plot()

            # ==========================================
            # RIGHT COLUMN: RESULTS
            # ==========================================
            with gr.Column(scale=1, elem_classes="result-card"):

                gr.Markdown("### 🚨 Forecast Results", elem_classes="sub-header")

                risk = gr.Textbox(label="Risk Level")
                advisory = gr.Textbox(label="Flood Advisory")
                peak_depth = gr.Textbox(label="Peak Flood Depth (MSL)")
                peak_time = gr.Textbox(label="Time of Peak")

                forecast_table = gr.Dataframe(
                    label="Detailed Forecast Table"
                )

                gr.Markdown("""
                **Disclaimer:** This system is intended for research and
                decision-support purposes and should not replace official
                flood warning systems.
                """)
        # Bind the click function for Tab 1
        submit_btn.click(
            fn=forecast_from_text,
            inputs=[rainfall_input, start_datetime, river_condition],
            outputs=[combined_plot, forecast_table, peak_depth, peak_time, risk, advisory]
        )
    # ==========================================
    # TAB 2: MODEL VALIDATION
    # ==========================================
    with gr.Tab("Model Validation"):
        with gr.Row():

            # LEFT COLUMN: Overall Testing Metrics
            with gr.Column(scale=1, elem_classes="result-card"):
                gr.Markdown("### 📊 Overall Testing Performance", elem_classes="sub-header")
                gr.Markdown(f"""
                | Metric | Value |
                |---------|---------|
                | **RMSE** | {overall_rmse:.4f} |
                | **MAE** | {overall_mae:.4f} |
                | **R²** | {overall_r2:.4f} |
                | **NSE** | {overall_nse:.4f} |
                """)

                gr.Markdown(f"""
                  ### Performance Interpretation

                  - **RMSE = {overall_rmse:.4f} m**

                    Indicates that prediction errors are generally less than 3 cm.

                  - **MAE = {overall_mae:.4f} m**

                    Indicates an average prediction error of approximately **{overall_mae*100:.2f} cm**.

                  - **R² = {overall_r2:.4f}**

                    Indicates that **{overall_r2*100:.2f}%** of observed flood-depth variability is explained by the model.

                  - **NSE = {overall_nse:.4f}**

                    Indicates excellent predictive performance and strong agreement between observed and predicted flood depths.

                  ---

                  **Overall, the developed ANN model demonstrates high accuracy and reliability for flood depth forecasting within the testing dataset.**
                  """)

            # RIGHT COLUMN: Validation Cases
            with gr.Column(scale=2, elem_classes="result-card"):
                gr.Markdown("### 🔍 Validation Case Studies", elem_classes="sub-header")
                gr.Markdown("Validation cases represent different 100-sample segments extracted from the testing dataset to visualize model performance across varying flood conditions.")

                validation_case = gr.Dropdown(
                    choices=list(VALIDATION_CASES.keys()),
                    value="Case A (0-99)",
                    label="Validation Case"
                )

                validation_plot = gr.Plot()

                # Grouping the small metrics boxes into one neat row
                with gr.Row():
                    rmse_box = gr.Textbox(label="RMSE")
                    mae_box = gr.Textbox(label="MAE")
                    r2_box = gr.Textbox(label="R²")
                    nse_box = gr.Textbox(label="NSE")

                case_interpretation = gr.Textbox(label="Case Interpretation", lines=4)

        # Bind the change function for Tab 2
        validation_case.change(
            fn=validation_dashboard,
            inputs=[validation_case],
            outputs=[validation_plot, rmse_box, mae_box, r2_box, nse_box, case_interpretation]
        )

def interpret_case_metrics(
    rmse,
    mae,
    r2,
    nse
):

    interpretation = []

    if rmse < 0.05:
        interpretation.append(
            "RMSE indicates very low prediction error."
        )
    else:
        interpretation.append(
            "RMSE indicates moderate prediction error."
        )

    interpretation.append(
        f"Average prediction error is approximately {mae*100:.2f} cm."
    )

    if r2 >= 0.90:
        interpretation.append(
            f"The model explains {r2*100:.2f}% of the observed variance, indicating an excellent fit."
        )
    elif r2 >= 0.75:
        interpretation.append(
            f"The model explains {r2*100:.2f}% of the observed variance, indicating a good fit."
        )
    else:
        interpretation.append(
            f"The model explains {r2*100:.2f}% of the observed variance."
        )

    if nse >= 0.75:
        interpretation.append(
            "NSE indicates excellent predictive performance."
        )
    elif nse >= 0.50:
        interpretation.append(
            "NSE indicates acceptable predictive performance."
        )
    else:
        interpretation.append(
            "NSE indicates limited predictive performance."
        )

    return "\n\n".join(
        interpretation
    )

# Finally, launch the app!
demo.launch(debug=True)