# Project-wide Gradle settings
# URL default backend (tanpa slash akhir di property; build.gradle menambahkan slash untuk BuildConfig)
# DEFAULT_SERVER_URL=https://ade-basirwfrd-child-monitor-server.hf.space

android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
