window.PRICING_ASSISTANT_MOCK_DATA = {
    acquisitionBids: [
        {
            orderId: 'SC-20260427-1008',
            docType: '收车单',
            city: '上海',
            store: '上海虹桥体验店',
            owner: '王凯',
            evaluator: '张三',
            status: '评估中',
            title: '2021款 特斯拉Model 3 后轮驱动版',
            brand: '特斯拉',
            year: '2021',
            regDate: '2021年8月',
            mileage: '4.8万公里',
            color: '红色',
            tags: ['企业收车', '车辆报价', '新能源'],
            dsi: 'DSI持续走高',
            vehicleSourceNo: '66621499',
            plateNo: '沪A8T321',
            vinLast4: '9K21',
            acquisitionTime: '2026-04-27 10:20',
            updatedAt: '2026-04-27 11:35',
            remark: '客户希望今日完成收车价确认，需优先出价。',
            ownerExpectedPrice: 25,
            appraiserRemark: '--',
            smartSalePrice: 25.69,
            smartPurchasePrice: 24.89,
            smartPricingReason: '--',
            consignmentType: '寄售企业',
            newCarResidualPrice: '',
            storeListingPrice: '',
            mediaListingPrice: '',
            gzListingPrice: '',
            gzDealPrice: '',
            otherReasoningPrice: '',
            salePrice: '',
            settlementPrice: '--',
            serviceFee: 0.8,
            serviceFeeRatio: '3.1%',
            pricingReason: '',
            finalBidPrice: 10.50,
            maxAcquisitionPrice: 10.50,
            expectedSalePrice: null,
            reasonablePriceRange: [11.38, 13.19],
            excellentPriceMax: 10.53,
            goodPriceMax: 11.38,
            normalPriceMax: 13.19,
            averagePriceMax: 13.99,
            cityCompetitiveness: { city: '洛阳', lowerThanPercent: 100, similarVehicleCount: null, rank: 1 },
            nationalCompetitiveness: { lowerThanPercent: 100, similarVehicleCount: 9, rank: 1 },
            turnoverEstimate: { daysRange: '15~25天' }
        },
        {
            orderId: 'SC-20260427-1017',
            docType: '收车单',
            city: '北京',
            store: '北京朝阳门店',
            owner: '李倩',
            evaluator: '张三',
            status: '收车中',
            title: '2021款 红旗H5 1.8T 智联旗享版',
            brand: '红旗',
            year: '2021',
            regDate: '2021年5月',
            mileage: '6.2万公里',
            color: '黑色',
            tags: ['家用车', '车辆报价', '非抵押车'],
            dsi: 'DSI持续走低',
            vehicleSourceNo: '66883021',
            plateNo: '京Q5H778',
            vinLast4: 'A613',
            acquisitionTime: '2026-04-26 16:45',
            updatedAt: '2026-04-27 09:18',
            remark: '评估师已完成初检，等待业务侧确认出价。',
            ownerExpectedPrice: 25,
            appraiserRemark: '--',
            smartSalePrice: 25.69,
            smartPurchasePrice: 24.89,
            smartPricingReason: '--',
            consignmentType: '寄售企业',
            newCarResidualPrice: '',
            storeListingPrice: '',
            mediaListingPrice: '',
            gzListingPrice: '',
            gzDealPrice: '',
            otherReasoningPrice: '',
            salePrice: '',
            settlementPrice: '--',
            serviceFee: 0.8,
            serviceFeeRatio: '3.1%',
            pricingReason: '',
            finalBidPrice: 10.50,
            maxAcquisitionPrice: 10.50,
            expectedSalePrice: null,
            reasonablePriceRange: [11.38, 13.19],
            excellentPriceMax: 10.53,
            goodPriceMax: 11.38,
            normalPriceMax: 13.19,
            averagePriceMax: 13.99,
            cityCompetitiveness: { city: '洛阳', lowerThanPercent: 100, similarVehicleCount: null, rank: 1 },
            nationalCompetitiveness: { lowerThanPercent: 100, similarVehicleCount: 9, rank: 1 },
            turnoverEstimate: { daysRange: '15~25天' }
        },
        {
            orderId: 'SC-20260427-1024',
            docType: '收车单',
            city: '北京',
            store: '北京-东城',
            owner: '赵明',
            evaluator: '邓如意',
            status: '待出价',
            title: '2022款 宝马X3 xDrive25i M运动套装',
            brand: '宝马',
            year: '2022',
            regDate: '2022年05月',
            mileage: '3.7万公里',
            color: '白色',
            tags: ['企业收车', '家用车', '车辆报价'],
            dsi: 'DSI持续走低',
            vehicleSourceNo: '66228018',
            plateNo: '京A****8',
            vinLast4: '8018',
            acquisitionTime: '2026-04-27 12:10',
            updatedAt: '2026-04-27 13:05',
            remark: '同款供给增加，建议结合整备成本谨慎出价。',
            ownerExpectedPrice: 25,
            appraiserRemark: '--',
            smartSalePrice: 25.69,
            smartPurchasePrice: 24.89,
            smartPricingReason: '--',
            consignmentType: '寄售企业',
            newCarResidualPrice: '',
            storeListingPrice: '',
            mediaListingPrice: '',
            gzListingPrice: '',
            gzDealPrice: '',
            otherReasoningPrice: '',
            salePrice: '',
            settlementPrice: '--',
            serviceFee: 0.8,
            serviceFeeRatio: '3.1%',
            pricingReason: '',
            finalBidPrice: 10.50,
            maxAcquisitionPrice: 10.50,
            expectedSalePrice: null,
            reasonablePriceRange: [11.38, 13.19],
            excellentPriceMax: 10.53,
            goodPriceMax: 11.38,
            normalPriceMax: 13.19,
            averagePriceMax: 13.99,
            cityCompetitiveness: { city: '洛阳', lowerThanPercent: 100, similarVehicleCount: null, rank: 1 },
            nationalCompetitiveness: { lowerThanPercent: 100, similarVehicleCount: 9, rank: 1 },
            turnoverEstimate: { daysRange: '15~25天' },
            quoteDetail: {
                aiSuggestedBid: 22.80,
                dealerBidRange: '22.40 - 23.10 万',
                retailRange: '24.60 - 25.80 万',
                avgDeal30d: 24.20,
                reconditioningCost: 0.35,
                estimatedGrossProfit: 1.05,
                supplyAdvice: '谨慎收车，建议控制收车价',
                conditionGrade: 'B+',
                conditionSummary: {
                    exterior: '轻微划痕，局部补漆',
                    interior: '正常磨损',
                    accident: '未见重大事故痕迹',
                    fireFlood: '未见异常',
                    tires: '前轮约 60%，后轮约 70%'
                }
            }
        }
    ],
    priceAdjustmentVehicles: [
        {
            vehicleSourceNo: 'P260421001',
            status: '可售',
            store: '上海虹桥体验店',
            title: '2021款 特斯拉Model 3 后轮驱动版',
            brand: '特斯拉',
            salePrice: 16.88,
            purchasePrice: 15.92,
            reconditioningCost: 0.18,
            regDate: '2021年8月',
            mileage: '4.8万公里',
            color: '红色',
            ageDays: 42,
            tags: ['新能源', '入库', '可售', 'ToC'],
            suggestion: '降价',
            suggestedDelta: -1000,
            reason: '线索质量低、库龄偏高、同城近30天同款价格下移，当前价格竞争力不足。',
            competitiveness: '偏低',
            lastAdjustmentAt: '2026-04-20',
            reservedAt: '-'
        },
        {
            vehicleSourceNo: 'P260421002',
            status: '已上架',
            store: '杭州滨江店',
            title: '2022款 比亚迪宋PLUS DM-i 110KM 旗舰PLUS',
            brand: '比亚迪',
            salePrice: 12.58,
            purchasePrice: 11.95,
            reconditioningCost: 0.12,
            regDate: '2022年6月',
            mileage: '3.6万公里',
            color: '白色',
            ageDays: 36,
            tags: ['新能源', '家用车', '个人自营', '可售'],
            suggestion: '保持',
            suggestedDelta: 0,
            reason: '同类样本价格区间稳定，当前询盘和利润空间较均衡。',
            competitiveness: '中',
            lastAdjustmentAt: '2026-04-18',
            reservedAt: '-'
        },
        {
            vehicleSourceNo: 'P260421003',
            status: '可售',
            store: '北京朝阳门店',
            title: '2020款 宝马3系 325Li M运动套装',
            brand: '宝马',
            salePrice: 18.98,
            purchasePrice: 17.80,
            reconditioningCost: 0.30,
            regDate: '2020年11月',
            mileage: '6.9万公里',
            color: '蓝色',
            ageDays: 57,
            tags: ['汽油', '家用车', '可售', '非抵押车'],
            suggestion: '降价',
            suggestedDelta: -1000,
            reason: '库龄偏长，周转压力高，价格高于相近里程样本。',
            competitiveness: '低',
            lastAdjustmentAt: '2026-04-12',
            reservedAt: '-'
        },
        {
            vehicleSourceNo: 'P260421004',
            status: '已预订',
            store: '北京-东城',
            title: '2023款 奥迪A4L 40 TFSI 豪华动感型',
            brand: '奥迪',
            salePrice: 22.68,
            purchasePrice: 21.30,
            reconditioningCost: 0.25,
            regDate: '2023年2月',
            mileage: '2.4万公里',
            color: '黑色',
            ageDays: 18,
            tags: ['汽油', '精品车', 'ToC', '已预订'],
            suggestion: '涨价',
            suggestedDelta: 1000,
            reason: '同配置样本供给少，预订热度高，可小幅上调挂牌价。',
            competitiveness: '高',
            lastAdjustmentAt: '2026-04-22',
            reservedAt: '2026-04-26'
        }
    ],
    mediaPricingDefault: {
        mediaRetailPrice: 18.6,
        acquisitionPriceRange: [16.8, 17.6],
        retailPriceRange: [18.2, 19.1],
        suggestedListingPrice: 18.8,
        confidence: 0.86,
        reason: '根据车型、上牌时间、里程、车况、城市及新能源行情综合估算',
        comparableVehicles: [
            { title: '2024款 理想L6 Pro', city: '上海', mileage: '3.2万公里', price: 18.9, source: '同城在售样本' },
            { title: '2024款 理想L6 Pro', city: '杭州', mileage: '3.8万公里', price: 18.4, source: '近似成交样本' },
            { title: '2024款 理想L6 Max', city: '上海', mileage: '2.9万公里', price: 19.3, source: '同品牌配置参考' }
        ]
    },
    mediaPricingResults: {
        '理想 L6': {
            mediaRetailPrice: 18.6,
            acquisitionPriceRange: [16.8, 17.6],
            retailPriceRange: [18.2, 19.1],
            suggestedListingPrice: 18.8,
            confidence: 0.86,
            reason: '根据理想 L6 同款样本、2024年上牌车源、3-4万公里区间、上海新能源行情及原版原漆车况综合估算',
            comparableVehicles: [
                { title: '2024款 理想L6 Pro', city: '上海', mileage: '3.2万公里', price: 18.9, source: '同城在售样本' },
                { title: '2024款 理想L6 Pro', city: '上海', mileage: '3.6万公里', price: 18.5, source: '近似成交样本' },
                { title: '2024款 理想L6 Max', city: '苏州', mileage: '3.1万公里', price: 19.2, source: '配置上沿参考' }
            ]
        }
    }
};
