# issue_lookup.py
ISSUE_LOOKUP = {
    "UPI": [
        "Amount Debited but Payment Failed",
        "UPI Registration Failed",
        "Bank Account Not Linking",
        "Mobile Number Not Registered",
        "Mobile Number Verification Failed",
        "SIM Verification Failed",
        "Device Binding Failed",
        "UPI ID Creation Failed",
        "UPI ID Already Exists",
        "Unable to Set UPI PIN",
        "UPI PIN Generation Failed",
        "UPI PIN Reset Failed",
        "Incorrect UPI PIN",
        "Forgot UPI PIN",
        "UPI PIN Locked",
        "Too Many Incorrect PIN Attempts",
        "UPI App Login Failed",
        "UPI App Crashing",
        "UPI App Not Responding",
        "Unable to Access UPI Services",
        "Bank Server Unavailable",
        "Payment Failed",
        "Payment Pending",
        "Payment Timed Out",
        "Transaction Timed Out",
        "Amount Debited but Beneficiary Not Credited",
        "Amount Debited but Transaction Failed",
        "Beneficiary Credited but Amount Debited Twice",
        "Duplicate Debit",
        "Duplicate Transaction",
        "Double Charge on Same Transaction",
        "Refund Not Received",
        "Refund Delayed",
        "Refund Failed",
        "Merchant Refund Pending",
        "Chargeback Not Processed",
        "Wrong Account Credited",
        "Wrong UPI ID Credited",
        "Transfer to Closed Account",
        "Beneficiary Not Credited",
        "Beneficiary Credit Delayed",
        "Payment Reversed Unexpectedly",
        "Payment Reversed After Success",
        "Auto-Debit Failed",
        "AutoPay Registration Failed",
        "AutoPay Cancellation Failed",
        "Standing Instruction Failed",
        "Subscription Payment Failed",
        "Recurring Payment Failed",
        "Mandate Registration Failed",
        "Mandate Modification Failed",
        "Mandate Cancellation Failed",
        "Mandate Executed Incorrectly",
        "Collect Request Failed",
        "Collect Request Not Received",
        "Collect Request Expired",
        "Fake Collect Request",
        "Fraudulent Collect Request",
        "Unauthorized UPI Transaction",
        "Suspicious UPI Transaction",
        "UPI Account Compromised",
        "UPI Fraud Complaint",
        "Phishing Through UPI",
        "QR Code Not Working",
        "QR Code Payment Failed",
        "QR Code Fraud",
        "Merchant QR Invalid",
        "Static QR Not Working",
        "Dynamic QR Not Generated",
        "Merchant Payment Not Received",
        "Merchant Settlement Delayed",
        "Merchant Settlement Failed",
        "Merchant Payment Pending",
        "UPI Lite Registration Failed",
        "UPI Lite Balance Not Updated",
        "UPI Lite Top-up Failed",
        "UPI Lite Balance Deducted Incorrectly",
        "UPI Lite Payment Failed",
        "UPI Daily Limit Exceeded",
        "UPI Transaction Limit Incorrect",
        "UPI Limit Reset Delay",
        "Bank Limit Mismatch",
        "Unable to Add Bank Account",
        "Unable to Remove Bank Account",
        "Primary Bank Account Not Updating",
        "Bank Account Mapping Incorrect",
        "Incorrect Account Selected for Payment",
        "Multiple Bank Accounts Conflicting",
        "UPI ID Not Found",
        "UPI Handle Not Recognized",
        "Invalid VPA",
        "VPA Verification Failed",
        "Beneficiary Verification Failed",
        "Transaction History Not Available",
        "Transaction History Incorrect",
        "UPI Passbook Not Updated",
        "Notification Not Received",
        "SMS Confirmation Not Received",
        "Payment Success but No Receipt Generated",
        "Payment Receipt Incorrect",
        "UPI Services Temporarily Unavailable",
        "UPI Profile Update Failed",
        "Mobile Number Change Not Reflected",
        "UPI Account Deactivation Failed"
    ],
    "Credit Card": [
        "Card Lost",
        "Card Stolen",
        "Unauthorized Transaction",
        "Fraudulent Transaction",
        "Fraudulent International Transaction",
        "Card Compromised",
        "Card Cloned",
        "Card Misused",
        "Suspicious Transaction",
        "Card Blocked Without Notice",
        "Card Block Request Not Processed",
        "Card Unblocking Delay",
        "Card Hotlisting Failed",
        "Card Replacement Delay",
        "Replacement Card Not Received",
        "Card Renewal Delay",
        "Renewed Card Not Received",
        "Card Activation Failed",
        "Card Activation Pending",
        "Card Not Activated",
        "Card PIN Generation Failed",
        "Card PIN Reset Failed",
        "PIN Not Received",
        "Forgot PIN Assistance",
        "Incorrect PIN Accepted",
        "Card Swipe Failed",
        "Contactless Payment Not Working",
        "Tap to Pay Failed",
        "Card Declined at POS",
        "Online Card Transaction Failed",
        "International Transaction Declined",
        "Domestic Transaction Declined",
        "E-commerce Transaction Failed",
        "Recurring Payment Failed",
        "Merchant Payment Failed",
        "Payment Pending",
        "Payment Not Reflected",
        "Amount Debited but Payment Failed",
        "Amount Debited but Merchant Not Credited",
        "Duplicate Transaction",
        "Duplicate Debit",
        "Double Charge on Same Transaction",
        "Refund Not Received",
        "Refund Delayed",
        "Merchant Refund Pending",
        "Chargeback Not Processed",
        "Chargeback Rejected",
        "Dispute Resolution Delay",
        "Wrong Billing",
        "Billing Dispute",
        "Incorrect Interest Charged",
        "Late Fee Charged Incorrectly",
        "Finance Charges Incorrect",
        "GST Charged Incorrectly",
        "Annual Fee Charged Incorrectly",
        "Annual Fee Reversal Not Processed",
        "Overlimit Fee Dispute",
        "Cash Advance Fee Dispute",
        "Minimum Due Incorrectly Calculated",
        "Outstanding Balance Incorrect",
        "Credit Limit Not Updated",
        "Incorrect Credit Limit Reduction",
        "Credit Limit Enhancement Pending",
        "Temporary Credit Limit Not Applied",
        "Available Credit Not Updated",
        "EMI Conversion Failed",
        "EMI Cancellation Failed",
        "EMI Paid but Still Showing Due",
        "EMI Schedule Incorrect",
        "Auto-Debit Failed",
        "Auto-Debit Registered Incorrectly",
        "Standing Instruction Failed",
        "Statement Not Generated",
        "Statement Not Received",
        "Incorrect Statement",
        "Missing Transactions in Statement",
        "Duplicate Transactions in Statement",
        "Reward Points Not Credited",
        "Reward Points Expired Incorrectly",
        "Reward Points Redemption Failed",
        "Cashback Not Credited",
        "Cashback Reversed Incorrectly",
        "Offer Benefit Not Applied",
        "Voucher Redemption Failed",
        "Credit Card Closure Delay",
        "Credit Card Closure Not Processed",
        "Closure Request Rejected",
        "Closed Card Still Active",
        "No Dues Certificate Not Issued",
        "Card Upgrade Not Processed",
        "Card Downgrade Without Consent",
        "Card Variant Change Pending",
        "Add-on Card Not Received",
        "Add-on Card Activation Failed",
        "Supplementary Card Issue",
        "Virtual Card Creation Failed",
        "Virtual Card Not Working",
        "Virtual Card Expired Incorrectly",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "Name Correction Pending",
        "KYC Pending for Credit Card",
        "Insurance Added Without Consent",
        "Credit Shield Cancellation Pending",
        "Credit Bureau Reporting Incorrect",
        "Card Delivery to Wrong Address",
        "Card Application Rejected Without Reason",
        "Card Issuance Delay"
    ],
    "Debit Card": [
        "Card Lost",
        "Card Stolen",
        "Unauthorized Transaction",
        "Unauthorized Debit",
        "Fraudulent Transaction",
        "Fraudulent International Transaction",
        "Card Compromised",
        "Card Cloned",
        "Suspicious Transaction",
        "Card Blocked Without Notice",
        "Card Block Request Not Processed",
        "Card Unblocking Delay",
        "Hotlisting Request Failed",
        "Debit Card Activation Failed",
        "Card Activation Pending",
        "Replacement Card Not Received",
        "Replacement Card Delay",
        "Renewal Card Not Received",
        "Debit Card Renewal Delay",
        "Debit Card Expired Incorrectly",
        "Card PIN Generation Failed",
        "Card PIN Reset Failed",
        "Forgot Debit Card PIN",
        "PIN Not Received",
        "Incorrect PIN Accepted",
        "ATM PIN Change Failed",
        "Card Swipe Failed",
        "POS Transaction Failed",
        "Contactless Payment Not Working",
        "Tap to Pay Failed",
        "Online Transaction Failed",
        "International Transaction Declined",
        "Domestic Transaction Declined",
        "Recurring Payment Failed",
        "Merchant Payment Failed",
        "Amount Debited but Merchant Not Credited",
        "Amount Debited but Transaction Failed",
        "Duplicate Debit",
        "Duplicate Transaction",
        "Double Charge on Same Transaction",
        "Refund Not Received",
        "Refund Delayed",
        "Merchant Refund Pending",
        "Chargeback Not Processed",
        "Dispute Resolution Delay",
        "Card Declined at POS",
        "Card Declined Online",
        "Card Not Supported by Merchant",
        "Insufficient Balance Error Despite Available Funds",
        "Daily Transaction Limit Issue",
        "Transaction Limit Not Updated",
        "ATM Withdrawal Charge Dispute",
        "POS Charge Dispute",
        "International Usage Not Enabled",
        "International Usage Disabled Without Consent",
        "Domestic Usage Disabled",
        "Online Usage Disabled",
        "Contactless Usage Disabled",
        "Card Linked Account Incorrect",
        "Wrong Account Debited",
        "Debit Card Not Delivered",
        "Card Delivered to Wrong Address",
        "Card Dispatch Delay",
        "Card Printing Delay",
        "Card Issuance Delay",
        "Debit Card Request Rejected",
        "Debit Card Upgrade Pending",
        "Debit Card Variant Change Pending",
        "Virtual Debit Card Not Generated",
        "Virtual Debit Card Not Working",
        "Virtual Card Expired Incorrectly",
        "Replacement PIN Mailer Not Received",
        "Debit Card Closure Delay",
        "Debit Card Closure Not Processed",
        "Card Still Active After Closure Request",
        "Card Linked to Closed Account",
        "Standing Instruction Failed",
        "Auto-Debit Failed",
        "Subscription Payment Failed",
        "Fuel Surcharge Reversal Not Received",
        "Cash Withdrawal Declined Despite Sufficient Balance",
        "Cash Withdrawal Pending",
        "Balance Inquiry Failed",
        "Mini Statement Not Available",
        "Card Authentication Failed",
        "3D Secure Authentication Failed",
        "OTP Not Received for Debit Card Transaction",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "Name Correction Pending",
        "KYC Pending for Debit Card",
        "Card Insurance Added Without Consent",
        "Debit Card Reward Points Not Credited",
        "Cashback Not Credited",
        "Offer Discount Not Applied",
        "Merchant Offer Not Applied",
        "Card Linked Wallet Payment Failed",
        "Card Verification Failed",
        "Card Tokenization Failed",
        "Tokenized Card Not Working",
        "Card Removed from Wallet Automatically",
        "Card Usage Notification Not Received",
        "SMS Alert Not Received",
        "Card Misused After Blocking"
    ],
    "ATM": [
        "Cash Not Dispensed but Account Debited",
        "Partial Cash Dispensed",
        "Wrong Amount Dispensed",
        "Excess Cash Dispensed",
        "ATM Withdrawal Failed",
        "ATM Withdrawal Pending",
        "Cash Withdrawal Declined Despite Sufficient Balance",
        "ATM Card Retained",
        "ATM Card Not Returned",
        "ATM Card Stuck",
        "ATM PIN Change Failed",
        "ATM PIN Generation Failed",
        "ATM PIN Reset Failed",
        "Incorrect PIN Accepted",
        "ATM Balance Inquiry Failed",
        "Mini Statement Not Printed",
        "ATM Receipt Not Printed",
        "Receipt Shows Incorrect Transaction",
        "ATM Screen Frozen",
        "ATM Touchscreen Not Working",
        "ATM Machine Out of Service",
        "ATM Power Failure During Transaction",
        "ATM Network Error",
        "ATM Session Timed Out",
        "ATM Camera Not Working",
        "ATM Security Concern",
        "ATM Skimming Fraud",
        "Card Cloning at ATM",
        "Unauthorized ATM Withdrawal",
        "Fraudulent ATM Transaction",
        "ATM Cash Deposit Failed",
        "Cash Deposit Pending",
        "Cash Deposited but Not Credited",
        "Partial Cash Deposit Credited",
        "Cheque Deposit Failed",
        "Cheque Deposited but Not Updated",
        "Cheque Deposit Pending",
        "CDM Not Accepting Cash",
        "CDM Cash Jam",
        "CDM Receipt Not Generated",
        "Deposit Receipt Missing",
        "ATM Dispensed Fake Currency",
        "ATM Dispensed Damaged Notes",
        "ATM Dispensed Torn Notes",
        "ATM Dispensed Soiled Notes",
        "Cash Dispensed in Wrong Denomination",
        "ATM Running Out of Cash Frequently",
        "ATM Not Dispensing Cash",
        "Cash Withdrawal Reversed Incorrectly",
        "Amount Debited Twice",
        "Duplicate ATM Withdrawal",
        "Duplicate Debit for Single Withdrawal",
        "Refund Not Received After ATM Failure",
        "ATM Dispute Not Resolved",
        "ATM Charge Dispute",
        "Foreign ATM Withdrawal Charge Dispute",
        "Interchange Fee Charged Incorrectly",
        "ATM Convenience Fee Incorrect",
        "ATM Transaction History Missing",
        "ATM Transaction History Incorrect",
        "Cash Withdrawal Limit Issue",
        "Daily Withdrawal Limit Incorrect",
        "Withdrawal Limit Not Updated",
        "ATM Rejecting Valid Card",
        "ATM Unable to Read Card",
        "Chip Card Read Error",
        "Magnetic Stripe Read Error",
        "Card Authentication Failed",
        "ATM Language Selection Not Working",
        "ATM Accessibility Issue",
        "Wheelchair Access Not Available",
        "Cash Withdrawal Delayed",
        "Deposit Reversal Delayed",
        "Cash Deposit Reversal Failed",
        "Card Block Request After ATM Fraud",
        "Card Blocking Delay After ATM Incident",
        "ATM Surveillance Footage Request",
        "ATM Complaint Not Resolved",
        "ATM Located at Unsafe Premises",
        "ATM Frequently Offline",
        "ATM Cash Reconciliation Delay",
        "Deposit Envelope Not Processed",
        "Envelope Deposit Missing",
        "ATM Cash Counter Error",
        "Cash Deposit Machine Out of Service",
        "Cash Deposit Machine Offline",
        "Cash Deposit Machine Not Accepting Notes",
        "Cash Deposit Machine Accepted Cash but Failed Transaction",
        "Cash Deposit Machine Accepted Cash but No Receipt",
        "Cash Deposit Machine Accepted Cash but Amount Incorrect",
        "ATM Software Error",
        "ATM Restart During Transaction",
        "Cash Withdrawal SMS Not Received",
        "Cash Deposit SMS Not Received",
        "ATM OTP Not Received",
        "Cash Withdrawal Successful but Balance Incorrect",
        "Balance Not Updated After Withdrawal",
        "Balance Not Updated After Deposit",
        "ATM Cardless Withdrawal Failed",
        "Cardless Withdrawal OTP Expired",
        "Cardless Withdrawal Pending",
        "ATM QR Withdrawal Failed",
        "ATM QR Code Not Working",
        "ATM Location Not Available in App",
        "ATM Cash Forecast Incorrect"
    ],
   "Internet Banking": [
        "Internet Banking Registration Failed",
        "Login Failed",
        "Invalid Username or Password",
        "Username Not Recognized",
        "Password Reset Failed",
        "Password Reset Link Expired",
        "Forgot Password Issue",
        "Account Locked",
        "User ID Locked",
        "Security Questions Not Accepted",
        "Two-Factor Authentication Failed",
        "OTP Not Received",
        "OTP Expired",
        "OTP Verification Failed",
        "Device Registration Failed",
        "Browser Compatibility Issue",
        "Net Banking Portal Not Accessible",
        "Website Down",
        "Server Unavailable",
        "Session Timed Out",
        "Unexpected Logout",
        "Dashboard Not Loading",
        "Transaction History Not Loading",
        "Transaction History Missing",
        "Statement Download Failed",
        "Statement Not Available",
        "E-Statement Not Received",
        "Account Balance Not Updated",
        "Incorrect Balance Displayed",
        "Fund Transfer Failed",
        "Fund Transfer Pending",
        "Fund Transfer Timed Out",
        "Amount Debited but Beneficiary Not Credited",
        "Amount Debited but Transfer Failed",
        "Duplicate Fund Transfer",
        "Transfer Reversed Unexpectedly",
        "Transfer Scheduled but Not Executed",
        "Standing Instruction Failed",
        "Scheduled Payment Failed",
        "Recurring Transfer Failed",
        "Beneficiary Addition Failed",
        "Beneficiary Activation Pending",
        "Beneficiary Verification Failed",
        "Beneficiary Removal Failed",
        "Beneficiary Modification Failed",
        "Incorrect Beneficiary Credited",
        "Transfer Limit Exceeded Incorrectly",
        "Daily Transfer Limit Not Updated",
        "NEFT Transfer Failed",
        "RTGS Transfer Failed",
        "IMPS Transfer Failed",
        "Bill Payment Failed",
        "Utility Bill Payment Pending",
        "Credit Card Bill Payment Failed",
        "Loan EMI Payment Failed",
        "Tax Payment Failed",
        "GST Payment Failed",
        "Investment Payment Failed",
        "Merchant Payment Failed",
        "Payment Gateway Error",
        "Auto-Debit Registration Failed",
        "Mandate Registration Failed",
        "Mandate Cancellation Failed",
        "AutoPay Setup Failed",
        "Profile Update Failed",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "Nominee Update Failed",
        "PAN Update Failed",
        "KYC Update Failed",
        "Profile Photo Upload Failed",
        "Cheque Book Request Failed",
        "Cheque Book Tracking Unavailable",
        "Stop Cheque Payment Failed",
        "Demand Draft Request Failed",
        "Fixed Deposit Opening Failed",
        "Recurring Deposit Opening Failed",
        "Loan Statement Download Failed",
        "Interest Certificate Not Available",
        "TDS Certificate Not Available",
        "Account Statement Incorrect",
        "Download Receipt Not Generated",
        "SMS Alert Not Received",
        "Email Alert Not Received",
        "Push Notification Not Received",
        "Security Alert Not Received",
        "Suspicious Login Detected",
        "Unauthorized Login Attempt",
        "Unauthorized Transaction",
        "Fraudulent Transaction",
        "Session Hijacking Concern",
        "Digital Signature Verification Failed",
        "Captcha Not Loading",
        "Captcha Verification Failed",
        "Internet Banking Access Blocked",
        "Dormant Internet Banking Account",
        "Account Mapping Incorrect",
        "Linked Account Not Visible",
        "Joint Account Not Visible",
        "Service Request Not Submitted",
        "Service Request Status Not Updated",
        "Complaint Registration Failed",
        "Complaint Status Not Updated",
        "Internet Banking Deactivation Failed"
    ],
    "Mobile Banking": [
        "Mobile Banking Registration Failed",
        "Unable to Register Mobile Banking",
        "Device Registration Failed",
        "Mobile Number Verification Failed",
        "Mobile Banking Login Failed",
        "Invalid Username or Password",
        "Biometric Login Failed",
        "Fingerprint Authentication Failed",
        "Face ID Authentication Failed",
        "MPIN Generation Failed",
        "MPIN Reset Failed",
        "Forgot MPIN",
        "Incorrect MPIN",
        "MPIN Locked",
        "OTP Not Received",
        "OTP Verification Failed",
        "OTP Expired",
        "App Crashing",
        "App Not Opening",
        "App Keeps Logging Out",
        "Session Timed Out",
        "App Running Slowly",
        "App Freezing",
        "Blank Screen After Login",
        "Server Unavailable",
        "Maintenance Downtime",
        "Internet Connection Error",
        "Unable to Access Mobile Banking",
        "Dashboard Not Loading",
        "Account Balance Not Updated",
        "Transaction History Not Loading",
        "Transaction History Missing",
        "Mini Statement Not Available",
        "Fund Transfer Failed",
        "Fund Transfer Pending",
        "Amount Debited but Beneficiary Not Credited",
        "Amount Debited but Transfer Failed",
        "Duplicate Fund Transfer",
        "Transfer Reversed Unexpectedly",
        "Beneficiary Addition Failed",
        "Beneficiary Activation Pending",
        "Beneficiary Verification Failed",
        "Beneficiary Modification Failed",
        "Beneficiary Removal Failed",
        "Incorrect Beneficiary Credited",
        "Daily Transfer Limit Issue",
        "Transfer Limit Not Updated",
        "NEFT Transfer Failed",
        "RTGS Transfer Failed",
        "IMPS Transfer Failed",
        "UPI Registration Failed",
        "UPI ID Creation Failed",
        "UPI PIN Reset Failed",
        "UPI Transaction Failed",
        "UPI Payment Pending",
        "QR Code Payment Failed",
        "Merchant Payment Failed",
        "Bill Payment Failed",
        "Credit Card Bill Payment Failed",
        "Loan EMI Payment Failed",
        "Recharge Failed",
        "Utility Bill Payment Pending",
        "AutoPay Registration Failed",
        "Standing Instruction Failed",
        "Auto-Debit Failed",
        "Cheque Book Request Failed",
        "Cheque Stop Payment Failed",
        "Fixed Deposit Opening Failed",
        "Recurring Deposit Opening Failed",
        "Loan Statement Download Failed",
        "Account Statement Download Failed",
        "Interest Certificate Download Failed",
        "Tax Certificate Not Available",
        "Profile Update Failed",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "PAN Update Failed",
        "Nominee Update Failed",
        "KYC Verification Pending",
        "KYC Update Failed",
        "Video KYC Failed",
        "SMS Alerts Not Received",
        "Push Notifications Not Received",
        "Email Alerts Not Received",
        "Security Alerts Not Received",
        "Unauthorized Login Attempt",
        "Unauthorized Transaction",
        "Fraudulent Transaction",
        "Account Access Blocked",
        "Suspicious Login Detected",
        "Device Change Verification Failed",
        "App Update Failed",
        "App Update Caused Login Issue",
        "Feature Missing After Update",
        "Dark Mode Display Issue",
        "Language Change Not Working",
        "Complaint Registration Failed",
        "Complaint Status Not Updated",
        "Service Request Not Submitted",
        "Service Request Status Not Updated",
        "Feedback Submission Failed",
        "Digital Token Not Generated",
        "Card Management Feature Not Working",
        "Mobile Banking Deactivation Failed"
    ],
    "Loans": [
        "Loan Application Rejected",
        "Loan Application Pending",
        "Loan Approval Delayed",
        "Loan Approval Rejected Without Reason",
        "Loan Processing Delay",
        "Loan Verification Pending",
        "Loan Document Verification Delay",
        "Loan Document Rejected",
        "Loan Agreement Not Received",
        "Loan Sanction Letter Not Received",

        "Loan Disbursement Delayed",
        "Loan Disbursement Failed",
        "Partial Loan Disbursement",
        "Incorrect Loan Amount Disbursed",
        "Loan Disbursed to Wrong Account",
        "Loan Disbursement Pending",
        "Loan Disbursement Reversed",
        "Top-up Loan Disbursement Delay",
        "Loan Cancellation Not Processed",
        "Loan Cancellation Request Rejected",

        "EMI Paid but Showing Due",
        "EMI Deducted Twice",
        "EMI Auto-Debit Failed",
        "EMI Debited Before Due Date",
        "EMI Debited After Due Date",
        "EMI Not Updated",
        "EMI Payment Failed",
        "EMI Payment Pending",
        "EMI Payment Reversed",
        "EMI Schedule Incorrect",

        "Incorrect EMI Amount",
        "EMI Increased Without Notice",
        "EMI Reduction Not Applied",
        "Loan Tenure Incorrect",
        "Loan Outstanding Balance Incorrect",
        "Interest Charged Incorrectly",
        "Excess Interest Charged",
        "Floating Interest Rate Not Updated",
        "Interest Certificate Not Issued",
        "Loan Statement Not Available",

        "Loan Statement Incorrect",
        "Repayment Schedule Not Received",
        "Repayment Schedule Incorrect",
        "Foreclosure Request Pending",
        "Foreclosure Not Processed",
        "Foreclosure Charges Incorrect",
        "Prepayment Not Updated",
        "Prepayment Penalty Dispute",
        "Part Payment Not Updated",
        "Part Payment Rejected",

        "Loan Closure Not Updated",
        "Loan Account Still Showing Active",
        "Loan Closure Delay",
        "Loan Closure Request Pending",
        "Closed Loan Still Active",
        "Loan Closure Certificate Not Issued",
        "NOC Delay",
        "NOC Not Issued",
        "No Dues Certificate Not Issued",
        "Loan Closure Confirmation Not Received",

        "Lien Not Removed",
        "Collateral Not Released",
        "Property Documents Not Returned",
        "Vehicle Hypothecation Not Removed",
        "Gold Collateral Not Returned",
        "Security Deposit Not Refunded",
        "Guarantee Release Pending",
        "Mortgage Release Pending",
        "Title Deed Not Returned",
        "Collateral Valuation Dispute",

        "Loan Account Freeze",
        "Loan Account Blocked",
        "Loan Account Access Denied",
        "Loan Account Mapping Incorrect",
        "Loan Account Missing",
        "Loan Details Not Visible",
        "Loan Balance Not Updated",
        "Loan History Missing",
        "Duplicate Loan Account",
        "Incorrect Loan Type",

        "Credit Bureau Not Updated",
        "CIBIL Not Updated After Loan Closure",
        "Loan Showing Active in Credit Report",
        "Wrong Loan Status in Credit Report",
        "Incorrect Outstanding in Credit Report",
        "Duplicate Loan in Credit Report",
        "Loan Default Reported Incorrectly",
        "Late Payment Reported Incorrectly",
        "Loan Written Off Incorrectly",
        "Credit Score Affected Due to Bank Error",

        "Loan Insurance Charged Without Consent",
        "Insurance Claim Not Processed",
        "Insurance Premium Incorrect",
        "Loan Subsidy Not Applied",
        "Interest Subsidy Not Credited",
        "Government Subsidy Pending",
        "Restructuring Request Pending",
        "Loan Moratorium Not Applied",
        "Settlement Amount Incorrect",
        "Settlement Letter Not Issued",

        "Recovery Agent Harassment",
        "Collection Calls After Loan Closure",
        "Wrong Recovery Notice",
        "Legal Notice Issued Incorrectly",
        "Loan Complaint Resolution Delay",
        "Branch Not Responding for Loan Query",
        "Customer Support Not Responding",
        "Loan Service Request Pending",
        "Loan Nominee Update Pending",
        "Loan KYC Pending"
    ],
   "Savings Account": [
        "Account Opening Delay",
        "Account Opening Rejected",
        "Account Not Activated",
        "Account Activation Pending",
        "Account Number Not Generated",
        "Welcome Kit Not Received",
        "Passbook Not Issued",
        "Cheque Book Not Received",
        "Debit Card Not Received",
        "Welcome Letter Not Received",

        "Account Freeze Without Notice",
        "Account Blocked",
        "Account Debit Blocked",
        "Account Credit Blocked",
        "Account Restricted",
        "Account Locked",
        "Dormant Account Activation Delay",
        "Inactive Account Not Reactivated",
        "Joint Account Not Updated",
        "Minor Account Conversion Pending",

        "Cash Deposit Not Reflected",
        "Cash Deposit Pending",
        "Cash Deposit Failed",
        "Cash Withdrawal Failed",
        "Cash Withdrawal Pending",
        "Wrong Balance Displayed",
        "Available Balance Incorrect",
        "Ledger Balance Incorrect",
        "Duplicate Debit",
        "Unauthorized Debit",

        "Unauthorized Credit",
        "Duplicate Credit",
        "Salary Credit Not Received",
        "Salary Credit Delayed",
        "Government Benefit Not Credited",
        "Pension Not Credited",
        "Interest Not Credited",
        "Interest Calculated Incorrectly",
        "TDS Deducted Incorrectly",
        "Minimum Balance Penalty Incorrect",

        "Wrong Charges Deducted",
        "Service Charges Incorrect",
        "Annual Maintenance Charges Incorrect",
        "SMS Charges Incorrect",
        "Cheque Bounce Charges Incorrect",
        "ECS Unauthorized Debit",
        "Standing Instruction Failed",
        "Auto Debit Failed",
        "Recurring Payment Failed",
        "Mandate Registration Failed",

        "NEFT Credit Not Received",
        "RTGS Credit Not Received",
        "IMPS Credit Not Received",
        "Fund Transfer Failed",
        "Fund Transfer Pending",
        "Beneficiary Not Credited",
        "Beneficiary Added Incorrectly",
        "Transaction Pending",
        "Transaction Reversed Incorrectly",
        "Duplicate Transaction",

        "Statement Not Available",
        "Statement Download Failed",
        "Passbook Not Updated",
        "Passbook Printing Failed",
        "Mini Statement Incorrect",
        "Transaction History Missing",
        "Transaction History Incorrect",
        "Account Balance Not Updated",
        "Account Summary Incorrect",
        "E-Statement Not Received",

        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "Name Correction Pending",
        "Nominee Addition Pending",
        "Nominee Update Pending",
        "Nominee Removal Pending",
        "PAN Update Failed",
        "Aadhaar Update Failed",
        "KYC Verification Pending",

        "KYC Status Not Updated",
        "Video KYC Failed",
        "CKYC Not Updated",
        "Account Conversion Pending",
        "Joint Holder Addition Pending",
        "Joint Holder Removal Pending",
        "Signature Update Pending",
        "Photo Update Pending",
        "Date of Birth Correction Pending",
        "Customer ID Mapping Incorrect",

        "Account Closure Delay",
        "Account Closure Not Processed",
        "Closed Account Still Active",
        "Closure Request Rejected",
        "Closure Confirmation Not Received",
        "No Dues Certificate Not Issued",
        "Remaining Balance Not Refunded",
        "Account Closure Charges Incorrect",
        "Closure Request Pending",
        "Account Reopened Without Consent",

        "SMS Alerts Not Received",
        "Email Alerts Not Received",
        "Push Notifications Not Received",
        "OTP Not Received",
        "Unauthorized Login Attempt",
        "Fraudulent Transaction",
        "Suspicious Account Activity",
        "Complaint Resolution Delay",
        "Service Request Pending",
        "Branch Not Responding"
    ],
    "Current Account": [
        "Current Account Opening Delay",
        "Current Account Opening Rejected",
        "Current Account Not Activated",
        "Account Activation Pending",
        "Business Account Verification Pending",
        "Customer ID Not Generated",
        "Welcome Kit Not Received",
        "Cheque Book Not Received",
        "Debit Card Not Received",
        "Welcome Letter Not Received",

        "Account Freeze Without Notice",
        "Account Blocked",
        "Debit Transactions Blocked",
        "Credit Transactions Blocked",
        "Account Restricted",
        "Account Locked",
        "Dormant Account Activation Delay",
        "Business Account Reactivation Pending",
        "Joint Signatory Not Updated",
        "Authorized Signatory Update Pending",

        "Cash Deposit Not Reflected",
        "Cash Deposit Pending",
        "Cash Deposit Failed",
        "Cash Withdrawal Failed",
        "Cash Withdrawal Pending",
        "Wrong Balance Displayed",
        "Available Balance Incorrect",
        "Ledger Balance Incorrect",
        "Duplicate Debit",
        "Unauthorized Debit",

        "Unauthorized Credit",
        "Duplicate Credit",
        "Bulk Payment Failed",
        "Vendor Payment Failed",
        "Salary Payment Failed",
        "Vendor Credit Delayed",
        "Interest Credit Not Received",
        "Bank Charges Incorrect",
        "Overdraft Interest Incorrect",
        "Minimum Balance Penalty Incorrect",

        "Service Charges Incorrect",
        "Annual Maintenance Charges Incorrect",
        "Cheque Bounce Charges Incorrect",
        "SMS Charges Incorrect",
        "ECS Unauthorized Debit",
        "Standing Instruction Failed",
        "Auto Debit Failed",
        "Mandate Registration Failed",
        "Mandate Cancellation Failed",
        "Recurring Payment Failed",

        "NEFT Transfer Failed",
        "RTGS Transfer Failed",
        "IMPS Transfer Failed",
        "Fund Transfer Failed",
        "Fund Transfer Pending",
        "Beneficiary Not Credited",
        "Beneficiary Addition Failed",
        "Beneficiary Verification Pending",
        "Beneficiary Modification Failed",
        "Duplicate Transaction",

        "Merchant Settlement Delayed",
        "Merchant Settlement Failed",
        "POS Settlement Pending",
        "QR Settlement Delayed",
        "Payment Gateway Settlement Failed",
        "Settlement Amount Incorrect",
        "Chargeback Not Processed",
        "Refund Not Received",
        "Refund Delayed",
        "Dispute Resolution Delay",

        "Statement Not Available",
        "Statement Download Failed",
        "Passbook Not Updated",
        "Transaction History Missing",
        "Transaction History Incorrect",
        "Account Summary Incorrect",
        "E-Statement Not Received",
        "Balance Confirmation Certificate Not Issued",
        "Account Certificate Not Issued",
        "Audit Statement Not Available",

        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "Name Correction Pending",
        "Authorized Signatory Change Pending",
        "Nominee Addition Pending",
        "Nominee Update Pending",
        "PAN Update Failed",
        "GST Details Not Updated",
        "KYC Verification Pending",

        "KYC Status Not Updated",
        "Re-KYC Pending",
        "Business Registration Documents Not Updated",
        "Signature Update Pending",
        "Company Name Change Pending",
        "Constitution Change Not Updated",
        "Customer ID Mapping Incorrect",
        "Branch Transfer Pending",
        "Account Conversion Pending",
        "Account Linking Failed",

        "Current Account Closure Delay",
        "Current Account Closure Not Processed",
        "Closed Account Still Active",
        "Closure Request Rejected",
        "Closure Confirmation Not Received",
        "Remaining Balance Not Refunded",
        "Closure Charges Incorrect",
        "No Dues Certificate Not Issued",
        "Account Closure Request Pending",
        "Account Reopened Without Consent",

        "SMS Alerts Not Received",
        "Email Alerts Not Received",
        "OTP Not Received",
        "Unauthorized Login Attempt",
        "Fraudulent Transaction",
        "Suspicious Account Activity",
        "Complaint Resolution Delay",
        "Service Request Pending",
        "Branch Not Responding",
        "Relationship Manager Not Responding"
    ],
    "Cheque Services": [
        "Cheque Book Request Failed",
        "Cheque Book Not Received",
        "Cheque Book Delivery Delayed",
        "Cheque Book Sent to Wrong Address",
        "Cheque Book Pages Missing",
        "Cheque Book Printed Incorrectly",
        "Cheque Book Lost in Transit",
        "Cheque Book Request Rejected",
        "Additional Cheque Book Not Issued",
        "Personalized Cheque Book Delay",

        "Cheque Deposit Failed",
        "Cheque Deposit Pending",
        "Cheque Deposited but Not Credited",
        "Cheque Cleared but Amount Not Credited",
        "Cheque Returned Without Reason",
        "Cheque Bounced Incorrectly",
        "Cheque Clearing Delayed",
        "Cheque Collection Delayed",
        "Cheque Sent for Collection but Not Updated",
        "Cheque Deposit Receipt Not Generated",

        "CTS Clearing Delay",
        "CTS Image Not Available",
        "Cheque Truncation Failed",
        "CTS Verification Failed",
        "Cheque Scanning Error",
        "Cheque Image Mismatch",
        "Cheque Signature Verification Failed",
        "Signature Mismatch Reported Incorrectly",
        "Cheque Processing Error",
        "Cheque Validation Failed",

        "Post-Dated Cheque Presented Early",
        "Post-Dated Cheque Not Presented",
        "Stale Cheque Rejected Incorrectly",
        "Future-Dated Cheque Rejected",
        "Cheque Validity Dispute",
        "Cheque Presented Multiple Times",
        "Duplicate Cheque Clearing",
        "Cheque Paid Twice",
        "Cheque Cleared Despite Stop Payment",
        "Cheque Not Presented to Bank",

        "Stop Payment Request Failed",
        "Stop Payment Not Processed",
        "Stop Payment Charges Incorrect",
        "Cheque Cleared After Stop Payment",
        "Stop Payment Confirmation Not Received",
        "Stop Payment Cancellation Failed",
        "Cheque Block Request Failed",
        "Cheque Series Block Not Updated",
        "Stop Payment Request Pending",
        "Stop Payment Applied to Wrong Cheque",

        "Cheque Bounce Charges Incorrect",
        "Cheque Return Charges Incorrect",
        "Wrong Penalty Charged",
        "Cheque Returned Due to Bank Error",
        "Cheque Returned Despite Sufficient Balance",
        "Cheque Dishonoured Incorrectly",
        "Cheque Return Memo Not Received",
        "Cheque Return Reason Incorrect",
        "Wrong Insufficient Funds Status",
        "Cheque Bounce Record Incorrect",

        "Demand Draft Issuance Delay",
        "Demand Draft Not Issued",
        "Demand Draft Lost",
        "Demand Draft Cancellation Delay",
        "Demand Draft Refund Pending",
        "Demand Draft Amount Incorrect",
        "Demand Draft Duplicate Issued",
        "Demand Draft Encashment Failed",
        "Demand Draft Expired",
        "Demand Draft Status Not Updated",

        "Pay Order Not Issued",
        "Pay Order Cancellation Failed",
        "Banker's Cheque Delay",
        "Banker's Cheque Not Delivered",
        "Banker's Cheque Lost",
        "Certified Cheque Request Failed",
        "Manager's Cheque Delay",
        "Cashier's Order Not Issued",
        "Instrument Verification Failed",
        "Instrument Cancellation Pending",

        "Cheque Status Not Updated",
        "Cheque Tracking Not Available",
        "Cheque Enquiry Not Responding",
        "Cheque History Missing",
        "Cheque Transaction Missing",
        "Cheque Number Mismatch",
        "Cheque Leaf Already Used Error",
        "Cheque Sequence Incorrect",
        "Cheque Register Not Updated",
        "Cheque Issuance Record Incorrect",

        "Crossed Cheque Cleared Incorrectly",
        "Bearer Cheque Payment Dispute",
        "Order Cheque Wrongly Paid",
        "Altered Cheque Accepted",
        "Forged Cheque Cleared",
        "Unauthorized Cheque Encashment",
        "Fraudulent Cheque Transaction",
        "Cheque Tampering Complaint",
        "MICR Code Error",
        "Cheque Complaint Resolution Delay"
    ],
   "Fixed Deposit": [
        "FD Opening Failed",
        "Fixed Deposit Creation Failed",
        "FD Account Not Created",
        "FD Account Activation Pending",
        "FD Opening Delayed",
        "FD Application Pending",
        "FD Request Rejected",
        "FD Not Linked to Savings Account",
        "FD Amount Debited but FD Not Created",
        "Joint FD Creation Failed",

        "FD Receipt Not Received",
        "FD Certificate Not Received",
        "Digital FD Receipt Not Available",
        "FD Advice Not Generated",
        "FD Details Not Visible",
        "FD Account Not Showing",
        "Incorrect FD Details",
        "FD Number Not Generated",
        "FD Confirmation Not Received",
        "FD Nominee Not Updated",

        "FD Interest Not Credited",
        "Incorrect Interest Credited",
        "Interest Rate Incorrect",
        "Interest Calculation Error",
        "Interest Payment Delayed",
        "Quarterly Interest Not Received",
        "Monthly Interest Not Received",
        "Cumulative Interest Incorrect",
        "TDS Deducted Incorrectly",
        "Interest Certificate Not Issued",

        "FD Maturity Amount Incorrect",
        "FD Maturity Date Incorrect",
        "FD Maturity Amount Not Credited",
        "FD Maturity Payment Delayed",
        "FD Maturity Proceeds Pending",
        "FD Matured but Still Active",
        "FD Maturity Advice Not Received",
        "Auto Credit on Maturity Failed",
        "FD Maturity Instruction Ignored",
        "FD Closure Pending After Maturity",

        "Premature FD Closure Failed",
        "Premature Closure Delayed",
        "Premature Closure Charges Incorrect",
        "Premature Closure Request Pending",
        "FD Closure Not Processed",
        "FD Closure Confirmation Not Received",
        "FD Closure Certificate Not Issued",
        "Closed FD Still Showing Active",
        "Remaining Amount Not Credited",
        "Premature Closure Interest Incorrect",

        "FD Auto Renewal Failed",
        "FD Auto Renewal Incorrect",
        "FD Renewed Without Consent",
        "FD Renewal Delayed",
        "FD Renewal Request Pending",
        "FD Renewal Interest Rate Incorrect",
        "FD Renewal Confirmation Not Received",
        "FD Renewal Not Reflected",
        "FD Renewal Rejected",
        "Partial Renewal Not Processed",

        "Nominee Addition Pending",
        "Nominee Update Pending",
        "Nominee Removal Pending",
        "Joint Holder Update Pending",
        "PAN Update Failed",
        "Address Update Pending",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "KYC Verification Pending",
        "KYC Status Not Updated",

        "Lien Marked Incorrectly",
        "Lien Not Removed",
        "FD Pledged Without Consent",
        "Loan Against FD Request Pending",
        "Loan Against FD Rejected",
        "Loan Against FD Disbursement Delayed",
        "Loan Against FD Interest Incorrect",
        "FD Security Release Pending",
        "FD Freeze Without Notice",
        "FD Account Blocked",

        "Statement Not Available",
        "Statement Download Failed",
        "Interest Statement Incorrect",
        "Tax Certificate Not Available",
        "Form 15G Processing Pending",
        "Form 15H Processing Pending",
        "TDS Certificate Not Available",
        "FD Balance Not Updated",
        "Transaction History Missing",
        "FD Passbook Not Updated",

        "Online FD Booking Failed",
        "Mobile Banking FD Creation Failed",
        "Internet Banking FD Opening Failed",
        "FD Modification Request Failed",
        "FD Transfer Between Branches Pending",
        "FD Complaint Resolution Delay",
        "Branch Not Responding",
        "Customer Support Not Responding",
        "Service Request Pending",
        "Fixed Deposit Account Mapping Incorrect"
    ],
    "Recurring Deposit": [
        "RD Opening Failed",
        "Recurring Deposit Creation Failed",
        "RD Account Not Created",
        "RD Account Activation Pending",
        "RD Opening Delayed",
        "RD Application Pending",
        "RD Request Rejected",
        "RD Amount Debited but Account Not Created",
        "Joint RD Creation Failed",
        "Recurring Deposit Not Linked to Savings Account",

        "RD Installment Not Debited",
        "RD Installment Debited Twice",
        "RD Installment Debited Late",
        "RD Installment Debited Incorrectly",
        "Auto-Debit Failed",
        "Standing Instruction Failed",
        "Mandate Registration Failed",
        "Mandate Cancellation Failed",
        "Recurring Payment Failed",
        "Missed Installment Not Updated",

        "RD Balance Not Updated",
        "RD Installment Not Reflected",
        "RD Passbook Not Updated",
        "RD Transaction History Missing",
        "RD Statement Not Available",
        "Statement Download Failed",
        "Incorrect Installment History",
        "RD Details Not Visible",
        "RD Account Not Showing",
        "Incorrect RD Details",

        "RD Interest Not Credited",
        "Incorrect Interest Credited",
        "Interest Rate Incorrect",
        "Interest Calculation Error",
        "Interest Payment Delayed",
        "Maturity Interest Incorrect",
        "TDS Deducted Incorrectly",
        "Interest Certificate Not Issued",
        "Tax Certificate Not Available",
        "Interest Statement Incorrect",

        "RD Maturity Amount Incorrect",
        "RD Maturity Date Incorrect",
        "RD Maturity Amount Not Credited",
        "RD Maturity Payment Delayed",
        "RD Matured but Still Active",
        "Maturity Proceeds Pending",
        "Maturity Advice Not Received",
        "Auto Credit on Maturity Failed",
        "Maturity Instruction Ignored",
        "RD Closure Pending After Maturity",

        "Premature RD Closure Failed",
        "Premature Closure Delayed",
        "Premature Closure Charges Incorrect",
        "Premature Closure Request Pending",
        "RD Closure Not Processed",
        "RD Closure Confirmation Not Received",
        "Closed RD Still Showing Active",
        "Remaining Balance Not Credited",
        "Premature Closure Interest Incorrect",
        "RD Closure Certificate Not Issued",

        "RD Renewal Failed",
        "RD Renewal Delayed",
        "RD Renewed Without Consent",
        "RD Renewal Request Pending",
        "Renewal Interest Rate Incorrect",
        "Renewal Confirmation Not Received",
        "Renewal Not Reflected",
        "Renewal Rejected",
        "Partial Renewal Not Processed",
        "Auto Renewal Failed",

        "Nominee Addition Pending",
        "Nominee Update Pending",
        "Nominee Removal Pending",
        "Joint Holder Update Pending",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "PAN Update Failed",
        "KYC Verification Pending",
        "KYC Status Not Updated",

        "Loan Against RD Request Pending",
        "Loan Against RD Rejected",
        "Loan Against RD Disbursement Delayed",
        "Loan Against RD Interest Incorrect",
        "RD Lien Marked Incorrectly",
        "Lien Not Removed",
        "RD Freeze Without Notice",
        "RD Account Blocked",
        "RD Security Release Pending",
        "RD Account Mapping Incorrect",

        "Online RD Booking Failed",
        "Internet Banking RD Opening Failed",
        "Mobile Banking RD Opening Failed",
        "RD Modification Request Failed",
        "Installment Amount Change Failed",
        "RD Transfer Between Branches Pending",
        "RD Complaint Resolution Delay",
        "Branch Not Responding",
        "Customer Support Not Responding",
        "Service Request Pending"
    ],
    "Insurance": [
        "Insurance Policy Purchase Failed",
        "Insurance Policy Not Issued",
        "Policy Issuance Delayed",
        "Policy Proposal Pending",
        "Policy Application Rejected",
        "Insurance Premium Debited but Policy Not Issued",
        "Policy Document Not Received",
        "Digital Policy Certificate Not Available",
        "Policy Number Not Generated",
        "Policy Details Not Visible",

        "Insurance Premium Payment Failed",
        "Premium Paid but Not Reflected",
        "Premium Debited Twice",
        "Premium Payment Pending",
        "Auto Debit Premium Failed",
        "Standing Instruction Failed",
        "Premium Receipt Not Generated",
        "Premium Receipt Not Received",
        "Premium Amount Incorrect",
        "Premium Due Date Incorrect",

        "Policy Renewal Failed",
        "Policy Renewal Delayed",
        "Policy Renewed Without Consent",
        "Renewal Premium Incorrect",
        "Renewal Confirmation Not Received",
        "Policy Lapsed Incorrectly",
        "Grace Period Not Applied",
        "Renewal Reminder Not Received",
        "Policy Reactivation Pending",
        "Renewal Request Rejected",

        "Claim Registration Failed",
        "Claim Submission Failed",
        "Claim Not Registered",
        "Claim Under Review for Long Time",
        "Claim Processing Delayed",
        "Claim Rejected Without Reason",
        "Claim Amount Incorrect",
        "Claim Settlement Delayed",
        "Claim Settlement Failed",
        "Partial Claim Settlement",

        "Cashless Claim Rejected",
        "Cashless Hospital Approval Delayed",
        "Hospital Not Listed",
        "Cashless Authorization Pending",
        "Reimbursement Claim Delayed",
        "Medical Bills Rejected",
        "Claim Documents Not Received",
        "Claim Documents Lost",
        "Claim Status Not Updated",
        "Claim Closure Without Resolution",

        "Policy Cancellation Failed",
        "Policy Cancellation Delayed",
        "Cancellation Request Pending",
        "Policy Cancelled Without Consent",
        "Refund Not Received After Cancellation",
        "Cancellation Charges Incorrect",
        "Policy Still Active After Cancellation",
        "Policy Closure Confirmation Not Received",
        "Free Look Cancellation Rejected",
        "Policy Surrender Pending",

        "Nominee Addition Pending",
        "Nominee Update Pending",
        "Nominee Removal Pending",
        "Beneficiary Details Incorrect",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "PAN Update Failed",
        "KYC Verification Pending",
        "KYC Status Not Updated",

        "Policy Coverage Incorrect",
        "Coverage Not Updated",
        "Incorrect Sum Insured",
        "Incorrect Policy Term",
        "Incorrect Policy Type",
        "Add-on Cover Not Activated",
        "Rider Not Added",
        "Rider Removal Failed",
        "Policy Modification Failed",
        "Policy Endorsement Pending",

        "Insurance Linked Loan Incorrect",
        "Credit Shield Insurance Issue",
        "Loan Insurance Charged Without Consent",
        "Insurance Premium Charged Incorrectly",
        "Duplicate Insurance Policy",
        "Duplicate Premium Deduction",
        "Insurance Account Mapping Incorrect",
        "Insurance Benefits Not Applied",
        "Maturity Benefit Not Received",
        "Survival Benefit Delayed",

        "Bonus Not Credited",
        "Loyalty Benefit Not Applied",
        "Fund Value Incorrect",
        "ULIP NAV Not Updated",
        "Policy Value Not Updated",
        "Statement Not Available",
        "Policy Statement Incorrect",
        "Tax Certificate Not Available",
        "Service Request Pending",
        "Complaint Resolution Delay"
    ],
    "Demat / Trading Account": [
        "Demat Account Opening Failed",
        "Demat Account Opening Delayed",
        "Trading Account Opening Failed",
        "Trading Account Activation Pending",
        "Demat Account Not Activated",
        "Trading Account Not Activated",
        "Account Verification Pending",
        "KYC Verification Pending",
        "CKYC Not Updated",
        "Account Application Rejected",

        "BO ID Not Generated",
        "Client ID Not Generated",
        "Demat Account Not Visible",
        "Trading Account Not Visible",
        "Linked Bank Account Not Updated",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "PAN Update Failed",
        "Nominee Addition Pending",

        "Nominee Update Pending",
        "Nominee Removal Pending",
        "Authorized Person Update Pending",
        "Signature Verification Failed",
        "Profile Update Failed",
        "Trading Login Failed",
        "Incorrect Login Credentials",
        "Password Reset Failed",
        "OTP Not Received",
        "Two-Factor Authentication Failed",

        "Trading Platform Not Loading",
        "Trading App Crashing",
        "Trading Website Down",
        "Session Timed Out",
        "Unexpected Logout",
        "Market Watch Not Loading",
        "Portfolio Not Loading",
        "Holdings Not Visible",
        "Positions Not Visible",
        "Order Book Not Loading",

        "Buy Order Failed",
        "Sell Order Failed",
        "Order Pending",
        "Order Rejected",
        "Order Cancelled Unexpectedly",
        "Order Modification Failed",
        "Order Cancellation Failed",
        "Partial Order Executed",
        "Duplicate Order Executed",
        "Order Executed at Incorrect Price",

        "Order Executed Late",
        "Stop Loss Order Failed",
        "Bracket Order Failed",
        "Cover Order Failed",
        "AMO Order Failed",
        "GTT Order Failed",
        "Intraday Order Failed",
        "Delivery Order Failed",
        "Margin Trading Not Available",
        "Margin Requirement Incorrect",

        "Margin Not Updated",
        "Margin Blocked Incorrectly",
        "Margin Released Late",
        "Insufficient Margin Error",
        "Funds Not Credited",
        "Funds Withdrawal Failed",
        "Funds Withdrawal Pending",
        "Payout Delayed",
        "Pay-In Not Reflected",
        "Ledger Balance Incorrect",

        "Holdings Not Updated",
        "Shares Not Credited",
        "Shares Debited Incorrectly",
        "Shares Transfer Failed",
        "Off-Market Transfer Failed",
        "Demat Debit Failed",
        "Corporate Action Not Updated",
        "Bonus Shares Not Credited",
        "Dividend Not Credited",
        "Rights Issue Not Reflected",

        "Stock Split Not Updated",
        "Merger Shares Not Credited",
        "IPO Allotment Not Reflected",
        "IPO Refund Pending",
        "IPO Application Failed",
        "Pledge Creation Failed",
        "Pledge Release Pending",
        "Unpledge Request Failed",
        "Lien Not Removed",
        "Freeze Instruction Not Applied",

        "Account Freeze Without Notice",
        "Trading Restricted",
        "Demat Account Blocked",
        "Inactive Account Not Reactivated",
        "Annual Maintenance Charges Incorrect",
        "Brokerage Charged Incorrectly",
        "DP Charges Incorrect",
        "Transaction Charges Incorrect",
        "GST Charged Incorrectly",
        "Interest Charged Incorrectly",

        "Contract Note Not Received",
        "Contract Note Incorrect",
        "Ledger Statement Not Available",
        "Holding Statement Not Available",
        "Capital Gains Statement Missing",
        "Tax P&L Report Incorrect",
        "Transaction History Missing",
        "Portfolio Value Incorrect",
        "Complaint Resolution Delay",
        "Service Request Pending"
    ],
    "Forex / International Transactions": [
        "Forex Card Application Failed",
        "Forex Card Issuance Delayed",
        "Forex Card Not Delivered",
        "Forex Card Activation Failed",
        "Forex Card PIN Generation Failed",
        "Forex Card PIN Reset Failed",
        "Forex Card Lost",
        "Forex Card Stolen",
        "Replacement Forex Card Not Received",
        "Forex Card Expired Incorrectly",

        "Forex Card Block Request Failed",
        "Forex Card Unblocking Delayed",
        "Unauthorized Forex Card Transaction",
        "Fraudulent International Transaction",
        "Card Cloning During International Usage",
        "International ATM Withdrawal Failed",
        "International POS Transaction Failed",
        "International Online Transaction Failed",
        "Contactless Payment Failed Abroad",
        "Merchant Declined Forex Card",

        "Forex Card Balance Not Updated",
        "Available Balance Incorrect",
        "Amount Debited but Merchant Not Credited",
        "Amount Debited but Transaction Failed",
        "Duplicate International Transaction",
        "Duplicate Debit",
        "Refund Not Received",
        "Refund Delayed",
        "Merchant Refund Pending",
        "Chargeback Not Processed",

        "Incorrect Currency Conversion",
        "Exchange Rate Applied Incorrectly",
        "Dynamic Currency Conversion Dispute",
        "Currency Conversion Charges Incorrect",
        "Markup Charges Incorrect",
        "Foreign Transaction Fee Incorrect",
        "International Usage Charges Incorrect",
        "Cash Withdrawal Charges Incorrect",
        "Cross Currency Fee Incorrect",
        "Forex Rate Mismatch",

        "Forex Card Reload Failed",
        "Forex Card Reload Pending",
        "Reload Amount Not Updated",
        "Reload Request Rejected",
        "Maximum Reload Limit Reached Incorrectly",
        "Minimum Reload Amount Error",
        "Forex Wallet Not Updated",
        "Multi-Currency Wallet Issue",
        "Currency Wallet Not Activated",
        "Wallet Balance Missing",

        "International Fund Transfer Failed",
        "International Fund Transfer Pending",
        "SWIFT Transfer Failed",
        "SWIFT Transfer Delayed",
        "SWIFT Reference Not Generated",
        "Beneficiary Not Credited",
        "Beneficiary Verification Failed",
        "Incorrect Beneficiary Details",
        "Transfer Reversed Unexpectedly",
        "Transfer Cancelled Without Reason",

        "Outward Remittance Failed",
        "Outward Remittance Delayed",
        "Inward Remittance Not Received",
        "Inward Remittance Delayed",
        "Wire Transfer Failed",
        "Wire Transfer Pending",
        "Correspondent Bank Delay",
        "Remittance Returned",
        "Remittance Returned Without Reason",
        "Purpose Code Rejected",

        "FEMA Declaration Rejected",
        "LRS Limit Exceeded Incorrectly",
        "LRS Declaration Pending",
        "International Transfer Limit Incorrect",
        "Document Verification Pending",
        "Passport Verification Failed",
        "Visa Document Verification Pending",
        "KYC Verification Pending",
        "PAN Verification Failed",
        "Address Verification Pending",

        "International Transaction OTP Not Received",
        "International Transaction Verification Failed",
        "3D Secure Authentication Failed",
        "International Merchant Verification Failed",
        "Cross Border Payment Failed",
        "Foreign Merchant Payment Pending",
        "Payment Gateway Rejected International Card",
        "International Subscription Payment Failed",
        "International Recurring Payment Failed",
        "Travel Booking Payment Failed",

        "Forex Card Closure Delayed",
        "Forex Card Closure Not Processed",
        "Remaining Balance Not Refunded",
        "Foreign Currency Refund Pending",
        "Unused Balance Redemption Failed",
        "Foreign Currency Conversion Delay",
        "Forex Account Closure Pending",
        "International Transaction History Missing",
        "Forex Statement Not Available",
        "Complaint Resolution Delay"
    ],
    "Wallet / Prepaid Card": [
        "Wallet Registration Failed",
        "Wallet Activation Failed",
        "Wallet Verification Pending",
        "Wallet KYC Pending",
        "Wallet KYC Verification Failed",
        "Wallet Upgrade Failed",
        "Wallet Creation Failed",
        "Wallet Login Failed",
        "Wallet Account Locked",
        "Wallet Account Blocked",

        "Prepaid Card Activation Failed",
        "Prepaid Card Not Delivered",
        "Replacement Prepaid Card Not Received",
        "Prepaid Card PIN Generation Failed",
        "Prepaid Card PIN Reset Failed",
        "Prepaid Card Lost",
        "Prepaid Card Stolen",
        "Prepaid Card Block Request Failed",
        "Prepaid Card Unblocking Delayed",
        "Prepaid Card Expired Incorrectly",

        "Wallet Balance Not Updated",
        "Available Balance Incorrect",
        "Wallet Top-up Failed",
        "Wallet Top-up Pending",
        "Wallet Top-up Reversed",
        "Amount Debited but Wallet Not Credited",
        "Wallet Load Failed",
        "Wallet Load Limit Incorrect",
        "Wallet Balance Missing",
        "Duplicate Wallet Credit",

        "Wallet Payment Failed",
        "Wallet Payment Pending",
        "Merchant Payment Failed",
        "Merchant Payment Pending",
        "Amount Debited but Merchant Not Credited",
        "Amount Debited but Transaction Failed",
        "Duplicate Transaction",
        "Duplicate Debit",
        "Transaction Timed Out",
        "Payment Reversed Unexpectedly",

        "Refund Not Received",
        "Refund Delayed",
        "Merchant Refund Pending",
        "Refund Credited to Wrong Wallet",
        "Chargeback Not Processed",
        "Dispute Resolution Delay",
        "Transaction Reversal Failed",
        "Transaction History Missing",
        "Transaction History Incorrect",
        "Payment Receipt Not Generated",

        "Wallet Transfer Failed",
        "Wallet to Bank Transfer Failed",
        "Wallet to Wallet Transfer Failed",
        "Bank to Wallet Transfer Failed",
        "Beneficiary Not Credited",
        "Transfer Pending",
        "Transfer Cancelled Unexpectedly",
        "Incorrect Beneficiary Credited",
        "Transfer Limit Exceeded Incorrectly",
        "Daily Transfer Limit Incorrect",

        "QR Code Payment Failed",
        "QR Code Not Working",
        "Merchant QR Invalid",
        "Static QR Payment Failed",
        "Dynamic QR Not Generated",
        "QR Code Expired",
        "Scan and Pay Failed",
        "Contactless Payment Failed",
        "NFC Payment Failed",
        "Wallet Tokenization Failed",

        "Unauthorized Wallet Transaction",
        "Fraudulent Wallet Transaction",
        "Wallet Account Compromised",
        "Phishing Fraud",
        "Fake Merchant Payment",
        "Unauthorized Wallet Access",
        "Suspicious Login Detected",
        "OTP Not Received",
        "OTP Verification Failed",
        "Two-Factor Authentication Failed",

        "Wallet Cashback Not Credited",
        "Reward Points Not Credited",
        "Voucher Redemption Failed",
        "Promo Code Not Applied",
        "Offer Benefit Not Applied",
        "Cashback Reversed Incorrectly",
        "Loyalty Points Expired Incorrectly",
        "Gift Card Redemption Failed",
        "Coupon Redemption Failed",
        "Referral Bonus Not Credited",

        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",
        "PAN Update Failed",
        "KYC Status Not Updated",
        "Wallet Closure Delay",
        "Wallet Closure Not Processed",
        "Wallet Still Active After Closure",
        "Remaining Wallet Balance Not Refunded",
        "Complaint Resolution Delay"
    ],
    "Customer Service": [
        "Complaint Resolution Delay",
        "Complaint Not Resolved",
        "Complaint Closed Without Resolution",
        "Complaint Closed Incorrectly",
        "Complaint Status Not Updated",
        "Complaint Escalation Pending",
        "Complaint Escalation Rejected",
        "Complaint Assigned to Wrong Team",
        "Complaint Not Registered",
        "Duplicate Complaint Created",

        "Customer Care Not Reachable",
        "Call Not Connected",
        "Call Dropped During Conversation",
        "Long Waiting Time",
        "Executive Not Available",
        "IVR Not Working",
        "IVR Incorrect Routing",
        "Callback Not Received",
        "Missed Callback Request",
        "Support Ticket Not Created",

        "Email Support Not Responding",
        "Delayed Email Response",
        "Incorrect Email Response",
        "Email Ticket Closed Incorrectly",
        "Chat Support Not Responding",
        "Live Chat Disconnected",
        "Chat Session Timed Out",
        "Virtual Assistant Unable to Help",
        "Support Portal Not Working",
        "Complaint Portal Not Accessible",

        "Relationship Manager Not Responding",
        "Relationship Manager Changed Without Notice",
        "Wrong Information Provided",
        "Incomplete Information Provided",
        "Misleading Guidance",
        "Conflicting Information from Staff",
        "Service Request Not Understood",
        "Repeated Requests for Same Information",
        "Customer Query Ignored",
        "Follow-up Not Done",

        "Service Request Pending",
        "Service Request Rejected",
        "Service Request Not Processed",
        "Service Request Delayed",
        "Service Request Closed Incorrectly",
        "Service Request Status Not Updated",
        "Request Assigned to Wrong Department",
        "Duplicate Service Request",
        "Request Cancellation Failed",
        "Request Modification Failed",

        "Poor Customer Service",
        "Staff Misbehavior",
        "Rude Customer Executive",
        "Unprofessional Behaviour",
        "Lack of Communication",
        "No Status Updates",
        "False Commitment by Staff",
        "Promised Callback Not Received",
        "Issue Escalated Multiple Times",
        "Repeated Follow-up Required",

        "Verification Call Not Received",
        "Verification Failed Incorrectly",
        "Identity Verification Delayed",
        "Customer Authentication Failed",
        "OTP Verification Failed",
        "Security Verification Delay",
        "Video Verification Not Scheduled",
        "Video Verification Failed",
        "Document Verification Delayed",
        "Documents Not Acknowledged",

        "Feedback Submission Failed",
        "Feedback Ignored",
        "Survey Link Not Working",
        "Complaint Reference Number Not Generated",
        "Reference Number Invalid",
        "Tracking Complaint Failed",
        "Tracking Information Incorrect",
        "Case History Missing",
        "Complaint Reopened Incorrectly",
        "Complaint Reassigned Incorrectly",

        "Bank Response Delayed",
        "No Resolution Timeline Provided",
        "Escalation Matrix Not Followed",
        "Senior Officer Not Responding",
        "Nodal Officer Not Responding",
        "Grievance Officer Not Responding",
        "Ombudsman Escalation Pending",
        "Customer Satisfaction Issue",
        "Support Quality Poor",
        "Customer Experience Issue",

        "Incorrect Complaint Categorization",
        "Complaint Routed to Wrong Team",
        "Resolution Not Matching Complaint",
        "Issue Repeated After Resolution",
        "Case Reopened Multiple Times",
        "Complaint Documentation Missing",
        "Evidence Not Reviewed",
        "Supporting Documents Ignored",
        "Resolution Confirmation Not Received",
        "Final Response Not Received"
    ],
    "Branch Services": [
        "Long Queue at Branch",
        "Excessive Waiting Time",
        "Token System Not Working",
        "Token Not Generated",
        "Branch Closed During Working Hours",
        "Branch Opened Late",
        "Branch Closed Early",
        "Branch Staff Not Available",
        "Insufficient Service Counters",
        "Branch Overcrowded",

        "Staff Misbehavior",
        "Unprofessional Behaviour",
        "Rude Branch Staff",
        "Incorrect Information Provided",
        "Service Denied Without Reason",
        "Staff Refused Request",
        "Manager Not Available",
        "Branch Manager Not Responding",
        "Relationship Manager Not Available",
        "Poor Customer Service",

        "Document Verification Delay",
        "Document Submission Not Acknowledged",
        "Documents Lost by Branch",
        "Document Verification Failed",
        "Original Documents Not Returned",
        "Document Upload Failed",
        "Application Not Processed",
        "Application Rejected Incorrectly",
        "Application Status Not Updated",
        "Application Pending",

        "Address Update Pending",
        "Mobile Number Update Pending",
        "Email ID Update Pending",
        "PAN Update Pending",
        "Aadhaar Update Pending",
        "Signature Update Pending",
        "Photograph Update Pending",
        "Name Correction Pending",
        "Date of Birth Correction Pending",
        "Customer ID Correction Pending",

        "KYC Verification Pending",
        "Re-KYC Pending",
        "Video KYC Assistance Not Provided",
        "CKYC Update Pending",
        "Nominee Addition Pending",
        "Nominee Update Pending",
        "Nominee Removal Pending",
        "Joint Holder Addition Pending",
        "Joint Holder Update Pending",
        "Authorized Signatory Update Pending",

        "Cheque Book Not Issued",
        "Passbook Not Issued",
        "Passbook Printing Failed",
        "Demand Draft Not Issued",
        "Pay Order Not Issued",
        "Bank Certificate Not Issued",
        "Account Statement Not Provided",
        "Interest Certificate Not Issued",
        "No Dues Certificate Not Issued",
        "Account Closure Certificate Not Issued",

        "Cash Deposit Counter Delay",
        "Cash Withdrawal Counter Delay",
        "Cash Deposit Receipt Not Provided",
        "Cash Withdrawal Issue",
        "Cash Counting Error",
        "Cash Shortage at Branch",
        "Cash Deposit Not Updated",
        "Cheque Deposit Not Processed",
        "Locker Access Delayed",
        "Locker Service Unavailable",

        "Account Opening Delay",
        "Account Closure Delay",
        "Loan Processing Delay",
        "Loan Document Delay",
        "Credit Card Application Delay",
        "Debit Card Request Delay",
        "ATM PIN Not Generated",
        "Card Delivery Status Not Available",
        "Service Request Pending",
        "Complaint Not Registered",

        "Branch Transfer Request Pending",
        "Home Branch Change Pending",
        "Wrong Branch Mapping",
        "Branch Code Incorrect",
        "Customer Record Not Found",
        "System Down at Branch",
        "Server Connectivity Issue",
        "Printer Not Working",
        "Biometric Device Not Working",
        "Branch Network Failure",

        "Complaint Resolution Delay",
        "Escalation Not Handled",
        "Branch Not Responding",
        "Repeated Branch Visits Required",
        "Appointment Not Honoured",
        "Appointment Scheduling Failed",
        "Customer Feedback Ignored",
        "Branch Cleanliness Issue",
        "Accessibility Issue at Branch",
        "Parking Facility Issue"
    ],
    "KYC / AML / Compliance": [
        "KYC Verification Pending",
        "KYC Verification Failed",
        "KYC Status Not Updated",
        "KYC Documents Under Review",
        "KYC Documents Rejected",
        "KYC Documents Not Received",
        "KYC Submission Not Acknowledged",
        "KYC Update Failed",
        "Re-KYC Pending",
        "Re-KYC Demand Without Reason",

        "Video KYC Failed",
        "Video KYC Pending",
        "Video KYC Session Disconnected",
        "Video KYC Appointment Not Scheduled",
        "Video KYC Verification Delayed",
        "Offline KYC Not Updated",
        "CKYC Not Updated",
        "CKYC Record Not Found",
        "CKYC Download Failed",
        "CKYC Synchronization Failed",

        "PAN Verification Failed",
        "PAN Not Linked",
        "PAN Details Incorrect",
        "PAN Update Pending",
        "Aadhaar Verification Failed",
        "Aadhaar Authentication Failed",
        "Aadhaar Not Linked",
        "Aadhaar Update Pending",
        "Identity Verification Failed",
        "Customer Verification Pending",

        "Address Verification Pending",
        "Address Update Pending",
        "Address Proof Rejected",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Name Correction Pending",
        "Date of Birth Correction Pending",
        "Signature Verification Failed",
        "Photograph Update Pending",
        "Customer Information Mismatch",

        "Document Upload Failed",
        "Document Upload Pending",
        "Document Verification Delayed",
        "Document Verification Failed",
        "Document Mismatch",
        "Document Expired",
        "Supporting Documents Rejected",
        "Additional Documents Requested",
        "Document Review Taking Too Long",
        "Duplicate KYC Request",

        "AML Verification Pending",
        "AML Verification Failed",
        "Compliance Verification Pending",
        "Compliance Hold on Account",
        "Account Frozen Due to KYC",
        "Account Frozen Due to AML",
        "Account Restricted Due to Compliance",
        "Debit Block Due to KYC",
        "Credit Block Due to Compliance",
        "Transaction Blocked Due to AML",

        "Transaction Under Compliance Review",
        "Large Transaction Verification Pending",
        "Source of Funds Verification Pending",
        "Enhanced Due Diligence Pending",
        "Risk Profile Update Pending",
        "Risk Category Incorrect",
        "Customer Risk Assessment Delayed",
        "Politically Exposed Person Verification Pending",
        "FATCA Declaration Pending",
        "CRS Declaration Pending",

        "FEMA Declaration Pending",
        "LRS Declaration Pending",
        "Beneficial Owner Verification Pending",
        "Business KYC Pending",
        "Company Documents Verification Pending",
        "GST Verification Pending",
        "Authorized Signatory Verification Pending",
        "Board Resolution Verification Pending",
        "Trust Verification Pending",
        "Partnership Verification Pending",

        "Nominee Verification Pending",
        "Guardian Verification Pending",
        "Minor Account KYC Pending",
        "Joint Holder KYC Pending",
        "KYC Expired Incorrectly",
        "Re-KYC Reminder After Completion",
        "KYC Completed but Account Restricted",
        "KYC Completed but Services Blocked",
        "KYC Not Reflected Across Accounts",
        "Complaint Resolution Delay",

        "Branch Not Responding",
        "Customer Support Not Responding",
        "Service Request Pending",
        "Verification Appointment Delayed",
        "Incorrect Compliance Notice",
        "Duplicate Compliance Request",
        "KYC Certificate Not Available",
        "Compliance Status Not Updated",
        "Verification Reference Number Not Generated",
        "Customer ID Verification Failed"
    ],
    "Pension / Government Schemes": [
        "Pension Not Credited",
        "Pension Credit Delayed",
        "Pension Amount Incorrect",
        "Family Pension Not Started",
        "Family Pension Delayed",
        "Arrears Not Credited",
        "Dearness Relief Not Updated",
        "Pension Revision Not Applied",
        "Pension Account Not Updated",
        "Pension Payment Stopped",

        "Life Certificate Not Submitted",
        "Life Certificate Verification Failed",
        "Life Certificate Pending",
        "Digital Life Certificate Failed",
        "Jeevan Pramaan Not Updated",
        "Life Certificate Status Not Updated",
        "Biometric Verification Failed",
        "Face Authentication Failed",
        "Pension Verification Pending",
        "Pensioner Identity Verification Failed",

        "Pension Account Freeze",
        "Pension Account Blocked",
        "Pension Account Mapping Incorrect",
        "Pension Transfer Request Pending",
        "Pension Branch Transfer Delayed",
        "Pension Account Reactivation Pending",
        "Nominee Update Pending",
        "Family Details Not Updated",
        "Mobile Number Not Updated",
        "Address Update Pending",

        "PMJDY Account Issue",
        "PMJDY Account Not Activated",
        "PMJDY Benefits Not Received",
        "PMJDY RuPay Card Not Received",
        "PMJDY Insurance Benefit Not Available",
        "PMJDY Overdraft Facility Not Available",
        "PMJDY Account Frozen",
        "PMJDY Aadhaar Linking Failed",
        "PMJDY Subsidy Not Credited",
        "PMJDY KYC Pending",

        "DBT Not Credited",
        "DBT Credit Delayed",
        "DBT Failed",
        "DBT Amount Incorrect",
        "Government Subsidy Not Received",
        "Scholarship Not Credited",
        "LPG Subsidy Not Credited",
        "Fertilizer Subsidy Not Credited",
        "Farmer Benefit Not Credited",
        "Welfare Scheme Benefit Not Received",

        "PM Kisan Installment Not Received",
        "PM Kisan Beneficiary Verification Pending",
        "PM Kisan Aadhaar Mismatch",
        "PM Kisan Bank Account Not Linked",
        "PM Kisan Payment Failed",
        "PM Kisan Registration Pending",
        "PM Kisan Status Not Updated",
        "PM Kisan Application Rejected",
        "PM Kisan Installment Delayed",
        "PM Kisan Correction Pending",

        "NPS Registration Failed",
        "NPS Contribution Not Updated",
        "NPS Withdrawal Delayed",
        "NPS Exit Request Pending",
        "NPS PRAN Not Generated",
        "NPS Statement Not Available",
        "NPS Nominee Update Pending",
        "NPS KYC Pending",
        "NPS Account Frozen",
        "NPS Pension Not Started",

        "APY Registration Failed",
        "APY Contribution Not Debited",
        "APY Contribution Debited Twice",
        "APY Exit Request Pending",
        "APY Nominee Update Pending",
        "APY Statement Not Available",
        "APY Account Status Incorrect",
        "APY Benefit Not Received",
        "APY Auto Debit Failed",
        "APY Pension Delay",

        "Government Scheme Registration Failed",
        "Government Scheme Application Pending",
        "Government Scheme Verification Pending",
        "Government Scheme Rejected",
        "Scheme Eligibility Incorrect",
        "Benefit Transfer Failed",
        "Benefit Verification Pending",
        "Scheme Account Mapping Incorrect",
        "Scheme Status Not Updated",
        "Duplicate Scheme Registration",

        "Complaint Resolution Delay",
        "Service Request Pending",
        "Branch Not Responding",
        "Customer Support Not Responding",
        "Certificate Not Issued",
        "Identity Verification Pending",
        "Aadhaar Verification Failed",
        "PAN Verification Failed",
        "KYC Verification Pending",
        "Document Verification Pending"
    ],
    "Lockers": [
        "Locker Allotment Pending",
        "Locker Allotment Rejected",
        "Locker Not Available",
        "Locker Waiting List Delay",
        "Locker Agreement Pending",
        "Locker Activation Delayed",
        "Locker Not Activated",
        "Locker Allocation Changed",
        "Locker Assignment Incorrect",
        "Locker Number Not Issued",

        "Locker Access Denied",
        "Locker Access Delayed",
        "Locker Access During Working Hours Denied",
        "Locker Closed Unexpectedly",
        "Locker Facility Temporarily Unavailable",
        "Locker Room Under Maintenance",
        "Locker Key Not Working",
        "Duplicate Locker Key Request Pending",
        "Locker Key Lost",
        "Locker Key Broken",

        "Locker Key Replacement Delay",
        "Locker Lock Damaged",
        "Locker Door Jammed",
        "Locker Unable to Open",
        "Locker Closed Without Notice",
        "Locker Operated Without Customer Presence",
        "Unauthorized Locker Access",
        "Locker Security Concern",
        "Locker Contents Verification Request",
        "Locker Inspection Delay",

        "Locker Rent Charged Incorrectly",
        "Locker Rent Debited Twice",
        "Locker Rent Refund Pending",
        "Locker Rent Waiver Not Applied",
        "Locker Charges Incorrect",
        "Locker Deposit Refund Pending",
        "Locker Security Deposit Incorrect",
        "GST Charged Incorrectly",
        "Penalty Charged Incorrectly",
        "Locker Rent Not Updated",

        "Locker Renewal Pending",
        "Locker Renewal Failed",
        "Locker Renewal Confirmation Not Received",
        "Locker Closure Pending",
        "Locker Closure Not Processed",
        "Locker Surrender Delay",
        "Locker Surrender Confirmation Not Received",
        "Closed Locker Still Active",
        "Locker Reallocation Delay",
        "Locker Waiting List Not Updated",

        "Nominee Addition Pending",
        "Nominee Update Pending",
        "Nominee Removal Pending",
        "Joint Holder Update Pending",
        "Authorized Person Update Pending",
        "KYC Verification Pending",
        "KYC Status Not Updated",
        "Registered Mobile Number Not Updated",
        "Email ID Not Updated",
        "Address Update Pending",

        "Locker Agreement Not Updated",
        "Locker Operation Register Incorrect",
        "Biometric Verification Failed",
        "Signature Verification Failed",
        "Identity Verification Pending",
        "Locker Visit Appointment Failed",
        "Locker Visit Scheduling Delay",
        "Locker Visit Cancelled",
        "Branch Not Responding",
        "Locker Officer Not Available",

        "Locker Insurance Issue",
        "Locker Insurance Not Activated",
        "Insurance Claim Delayed",
        "Insurance Premium Incorrect",
        "Locker Damage Complaint",
        "Water Damage to Locker",
        "Fire Safety Concern",
        "Locker CCTV Concern",
        "Locker Privacy Concern",
        "Locker Security Deposit Not Refunded",

        "Locker Inventory Verification Delay",
        "Locker Complaint Resolution Delay",
        "Locker Complaint Not Resolved",
        "Service Request Pending",
        "Service Request Rejected",
        "Locker Documentation Missing",
        "Locker Records Incorrect",
        "Locker Transfer Request Pending",
        "Locker Transfer Rejected",
        "Locker Branch Transfer Delay",

        "Digital Locker Access Failed",
        "Smart Locker Authentication Failed",
        "OTP Not Received",
        "Access Token Expired",
        "Biometric Device Not Working",
        "Locker App Not Working",
        "Locker Booking Failed",
        "Locker Reservation Pending",
        "Customer Support Not Responding",
        "Relationship Manager Not Responding"
    ],
    "Merchant Services / POS": [
        "POS Machine Not Working",
        "POS Machine Activation Failed",
        "POS Installation Delayed",
        "POS Machine Replacement Delay",
        "POS Machine Damaged",
        "POS Machine Not Delivered",
        "POS Machine Battery Issue",
        "POS Machine Connectivity Issue",
        "POS Machine Software Error",
        "POS Machine Frozen",

        "Card Payment Failed",
        "Contactless Payment Failed",
        "Chip Card Read Error",
        "Swipe Transaction Failed",
        "Tap to Pay Failed",
        "QR Code Payment Failed",
        "UPI QR Not Working",
        "Dynamic QR Not Generated",
        "Static QR Invalid",
        "Payment Declined Incorrectly",

        "Amount Debited but Merchant Not Credited",
        "Merchant Settlement Pending",
        "Merchant Settlement Delayed",
        "Settlement Failed",
        "Settlement Amount Incorrect",
        "Partial Settlement Received",
        "Duplicate Settlement",
        "Settlement Reversed",
        "Settlement Report Incorrect",
        "Settlement History Missing",

        "Merchant Refund Failed",
        "Merchant Refund Pending",
        "Refund Amount Incorrect",
        "Refund Not Received by Customer",
        "Chargeback Raised Incorrectly",
        "Chargeback Not Processed",
        "Chargeback Rejected",
        "Dispute Resolution Delay",
        "Merchant Liability Dispute",
        "Transaction Reversal Failed",

        "Merchant Registration Failed",
        "Merchant Onboarding Delayed",
        "Merchant Verification Pending",
        "Merchant KYC Pending",
        "Merchant KYC Failed",
        "Merchant Profile Update Failed",
        "Business Details Not Updated",
        "Bank Account Not Linked",
        "GST Details Not Updated",
        "PAN Verification Failed",

        "Merchant Login Failed",
        "Merchant Portal Not Working",
        "Merchant Dashboard Not Loading",
        "Transaction History Missing",
        "Sales Report Incorrect",
        "Daily Sales Report Missing",
        "Monthly Statement Not Available",
        "Settlement Report Download Failed",
        "Invoice Generation Failed",
        "Receipt Not Generated",

        "Merchant QR Activation Failed",
        "Merchant QR Not Delivered",
        "QR Sticker Not Received",
        "Sound Box Not Working",
        "Sound Box Activation Failed",
        "Payment Notification Not Received",
        "SMS Alerts Not Received",
        "Email Alerts Not Received",
        "Push Notifications Not Received",
        "Settlement SMS Not Received",

        "Merchant Discount Rate Incorrect",
        "Transaction Charges Incorrect",
        "Rental Charges Incorrect",
        "Annual Maintenance Charges Incorrect",
        "Service Charges Incorrect",
        "GST Charged Incorrectly",
        "Penalty Charged Incorrectly",
        "POS Rental Refund Pending",
        "Wrong Charges Deducted",
        "Fee Waiver Not Applied",

        "International Card Payment Failed",
        "DCC Charge Dispute",
        "Foreign Currency Settlement Delay",
        "Recurring Payment Failed",
        "Subscription Payment Failed",
        "EMI Transaction Failed",
        "Cash at POS Failed",
        "Cash Withdrawal at POS Failed",
        "Cashback at POS Failed",
        "Offline Transaction Failed",

        "Complaint Resolution Delay",
        "Service Request Pending",
        "Branch Not Responding",
        "Relationship Manager Not Responding",
        "Customer Support Not Responding",
        "Technician Visit Delayed",
        "POS Maintenance Pending",
        "Device Pickup Delayed",
        "Merchant Account Blocked",
        "Merchant Account Mapping Incorrect"
    ],
    "Agriculture / Priority Sector Loans": [
        "Agriculture Loan Application Pending",
        "Agriculture Loan Application Rejected",
        "Crop Loan Approval Delayed",
        "Crop Loan Verification Pending",
        "Loan Document Verification Delayed",
        "Loan Sanction Letter Not Received",
        "Loan Disbursement Delayed",
        "Loan Disbursement Failed",
        "Partial Loan Disbursement",
        "Loan Amount Incorrectly Disbursed",

        "Crop Loan Not Credited",
        "Kisan Credit Card Application Pending",
        "Kisan Credit Card Not Issued",
        "Kisan Credit Card Activation Failed",
        "Kisan Credit Card Renewal Delayed",
        "Kisan Credit Card Limit Not Updated",
        "Kisan Credit Card Blocked",
        "Kisan Credit Card Replacement Pending",
        "Kisan Credit Card PIN Generation Failed",
        "Kisan Credit Card Lost",

        "KCC Transaction Failed",
        "KCC Cash Withdrawal Failed",
        "KCC Balance Not Updated",
        "KCC Interest Charged Incorrectly",
        "KCC Statement Not Available",
        "KCC Renewal Request Pending",
        "KCC Closure Pending",
        "KCC Limit Enhancement Pending",
        "KCC Limit Reduced Incorrectly",
        "KCC Account Freeze",

        "Interest Subsidy Not Applied",
        "Interest Subsidy Delayed",
        "Government Subsidy Not Credited",
        "Agriculture Subsidy Pending",
        "PM-KISAN Credit Not Received",
        "Crop Insurance Premium Deducted Incorrectly",
        "Crop Insurance Not Linked",
        "Crop Insurance Claim Pending",
        "Crop Insurance Claim Rejected",
        "Crop Insurance Settlement Delayed",

        "EMI Paid but Showing Due",
        "EMI Auto Debit Failed",
        "EMI Deducted Twice",
        "EMI Amount Incorrect",
        "Repayment Schedule Incorrect",
        "Loan Outstanding Balance Incorrect",
        "Interest Calculation Incorrect",
        "Penalty Charged Incorrectly",
        "Loan Statement Not Available",
        "Interest Certificate Not Issued",

        "Loan Restructuring Request Pending",
        "Natural Calamity Relief Not Applied",
        "Moratorium Not Applied",
        "Loan Rescheduling Delayed",
        "Debt Relief Scheme Not Applied",
        "Waiver Benefit Not Applied",
        "Loan Settlement Amount Incorrect",
        "Prepayment Not Updated",
        "Foreclosure Request Pending",
        "Foreclosure Charges Incorrect",

        "Loan Closure Not Updated",
        "Loan Account Still Active",
        "Loan Closure Certificate Not Issued",
        "No Dues Certificate Not Issued",
        "NOC Delay",
        "Collateral Not Released",
        "Land Documents Not Returned",
        "Lien Not Removed",
        "Mortgage Release Pending",
        "Closed Loan Still Showing Active",

        "Priority Sector Loan Not Classified Correctly",
        "MSME Loan Classified Incorrectly",
        "Agriculture Loan Category Incorrect",
        "Loan Purpose Recorded Incorrectly",
        "Farmer Category Not Updated",
        "Marginal Farmer Status Incorrect",
        "Small Farmer Status Incorrect",
        "Tenant Farmer Verification Pending",
        "Land Ownership Verification Failed",
        "Revenue Record Verification Pending",

        "KYC Verification Pending",
        "KYC Status Not Updated",
        "Aadhaar Verification Failed",
        "PAN Verification Failed",
        "Registered Mobile Number Not Updated",
        "Address Update Pending",
        "Nominee Update Pending",
        "Service Request Pending",
        "Branch Not Responding",
        "Agriculture Officer Not Responding",

        "Recovery Notice Issued Incorrectly",
        "Recovery Agent Harassment",
        "Wrong Loan Default Reported",
        "Credit Bureau Not Updated",
        "Duplicate Loan Account",
        "Loan Account Mapping Incorrect",
        "Complaint Resolution Delay",
        "Customer Support Not Responding",
        "Loan Records Missing",
        "Loan Transaction History Incorrect"
    ]
}