# severity.py
BASE_SEVERITY = {
    "Unauthorized Transaction": 10, "Fraud": 10, "Phishing / Vishing Attack": 10,
    "SIM Swap Fraud": 10, "OTP Fraud": 10, "Account Takeover": 10,
    "Cyber Fraud / Online Scam": 10, "Identity Theft": 10, "Mule Account Activity": 10,
    "Coercive Recovery Calls": 9, "Recovery Agent Harassment": 9, "ATM Fraud / Skimming": 10,
    "Wrong Amount Dispensed": 9, "Cash Deposited at CDM Not Credited": 9,
    "Investment Fraud via Bank Channel": 10, "Health Insurance Cashless Denial": 9,
    "Claim Rejected Without Reason": 9, "DBT Credit Not Received": 9,
    "Pension Credit Delayed": 9, "CIBIL Not Updated After Loan Closure": 9,
    "Amount Deducted Not Reversed": 8, "Cash Not Dispensed But Account Debited": 8,
    "Account Freeze / Hold": 8, "AML Hold on Account": 8, "Wrong EMI Deduction": 8,
    "Loan Processing Delay": 7, "Disbursement Not Done": 8,
    "NOC Not Issued After Full Repayment": 7, "RTGS Amount Not Credited to Beneficiary": 8,
    "IMPS Failure With Amount Deducted": 8, "NEFT Transfer Delayed Beyond RBI Timeline": 7,
    "Cheque Bounce Due to Bank Error": 8, "Wrong Account Debited": 8,
    "Foreclosure Not Processed": 7, "FD Maturity Amount Not Credited": 8,
    "Unauthorized Account Closure": 8, "Premium Deducted But Policy Not Issued": 8,
    "Double Premium Deduction": 8, "Shares Debited Without Trade": 8,
    "Wrong Exchange Rate Applied": 7, "International Transaction Blocked": 7,
    "KYC Update Rejected": 7, "Incorrect CIBIL Reporting by Bank": 8,
    "Misleading Information Given by Agent": 7, "Incorrect Advice Leading to Financial Loss": 8,
    "Remittance Not Received by Beneficiary": 8, "Locker Access Denied": 7,
    "Discriminatory Treatment": 7, "Senior Citizen / Differently Abled Not Assisted": 7,
    "Payment Pending": 5, "Duplicate Debit": 6, "Beneficiary Not Credited": 6,
    "Refund Not Received": 5, "Card Blocked Without Notice": 6, "Card Unblocking Delay": 5,
    "Login Failure": 4, "OTP Not Received": 5, "Account Not Activated": 5,
    "Premature Withdrawal Rejected": 5, "Complaint Closed Without Resolution": 6,
    "NACH Mandate Not Registered": 5, "Standing Instruction Failed": 5,
    "EMI Not Processed": 6, "Policy Lapsed Despite Premium Payment": 6,
    "Claim Processing Delay": 6, "Foreclosure Charges Dispute": 5,
    "Pre-payment Penalty Dispute": 5, "Forex Card Loading Failure": 5,
    "IPO Refund Not Received": 6, "SIP Start / Stop Failure": 4,
    "Cheque Clearance Delay": 5, "Stop Payment Not Executed": 6
}
